### ISSUE TITLE
Out of memory when writing a large file

### ISSUE THREAD

**Issue by aalexgabi** [GoogleCloudPlatform/gcsfuse#363] opened 2019-11-19 11:40 UTC
On a machine with 16G of RAM when I launch this:
```
$ dd if=/dev/zero of=10G bs=1M count=10240 conv=fdatasync status=progress
10734272512 bytes (11 GB, 10 GiB) copied, 273 s, 39.3 MB/s 
dd: fdatasync failed for '10G': Software caused connection abort
dd: fsync failed for '10G': Transport endpoint is not connected
dd: closing output file '10G': Transport endpoint is not connected
```
I get this error:
```
fatal error: runtime: out of memory
```
It does not always happen.
Do you have an idea what causes this?

**Comment by gaul** [comment] 2021-03-25 00:53
Duplicate of #505. Please test the proposed PR referenced there.

**Closed** 2021-03-25 20:24 UTC
