### ISSUE TITLE
Monitor status of gcsfuse

### ISSUE THREAD

**Issue by OliverDBA** [GoogleCloudPlatform/gcsfuse#521] opened 2021-04-21 12:41 UTC
Hi,

we are running gcsfuse 0.34.1 on Linux. Quite frequently we get the error 
    Mountpoint not connected
But if we check via ps the gcsfuse is process fot this mount point is available

How can we check, if the Mount point is correctly available:

- ps -ef|grep gcsfuse  will show a running process, even if connection did fail after some time
- ls -l mountpoint ora df -h will take minutes before timing out
- touch file on mount point also takes a long time to fail, if connection is not working

Is there another way to monitor and re-mount automatically?

**Comment by lezh** [comment] 2021-04-23 00:12
Is there a way to reproduce this error?

**Comment by OliverDBA** [comment] 2021-04-23 15:09
Unfortunately not. It is affecting us on different Redhat 7.9 servers, but no pattern visible.
If I run with debug_gcs then there are no details in, using the debug_https, the logfile is flooded with entries and nearly not readable any longer.

**Comment by lezh** [comment] 2021-04-23 18:17
This might be a FUSE issue, rather than gcsfuse issue.

**Comment by OliverDBA** [comment] 2021-04-26 16:20
I did some more investigation.
If there are too many processes using the gcsfuse mount, the gcsfuse process will be there but it will be unaccessible. Also unmounting is hanging.
Solution: Kill all processes which are using the gcsfuse mount and after that unmount and mount it

**Comment by lezh** [comment] 2021-04-26 18:15
@OliverDBA Thanks for the update! How many is "too many"?

**Comment by OliverDBA** [comment] 2021-04-26 18:26
there were about 300 processes running and the processes. 50 to 60 processes were writing to one logfile each, but no longer actively

**Comment by ashmeenkaur** [comment] 2023-07-20 15:14
Hi @OliverDBA, we are not able to reproduce this with the latest GCSFuse version (v1.0.0). I am closing this issue for now but feel free to reopen in case the issue persists.

Thanks,
Ashmeen

**Closed by ashmeenkaur** 2023-07-20 15:14 UTC
Labels: bug, p1
