### ISSUE TITLE
gcsfuse 0.39.0 - no such file or directory

### ISSUE THREAD

**Issue by Tobrek** [GoogleCloudPlatform/gcsfuse#580] opened 2021-12-16 13:53 UTC
This morning i provisioned a new server using ansible.
For nginx i mounted a directory using gcsfuse 0.39.0. When starting nginx it fails with error message:
`Dec 16 12:51:28 my-server nginx[27861]: nginx: [emerg] BIO_new_file("/etc/path/to/file/my-file") failed (SSL: error:02001002:system library:fopen:No such file or directory`
When coping the path and try `ls -l` it also complains about file not found. Using `ls` a second time (delete last char and auto complete) the file is found and nginx can use it after restart (and complains about the next "missing" file ...).

After downgrade to version 0.38.0 it works as expected.

As mount option just "only_dir" is used.

**Comment by Ovec** [comment] 2021-12-16 14:53
I have the same issue, right after container mounts bucket, request for file fails with following error:
```
{
  "error": {
    "code": 404,
    "message": "No such object: bucket/tracking/track.min.js/",
    "errors": [
      {
        "message": "No such object: bucket/tracking/track.min.js/",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
```
After cd into folder the response is:
`gcs: 2021/12/16 14:46:53.056405 Req             0x21: -> Read("tracking/track.min.js", [0, 8844)) (38.214388ms): OK`

After a while error is back.

**Comment by lezh** [comment] 2021-12-16 21:13
@Ovec Are you also using "--only-dir" option?

**Comment by lezh** [comment] 2021-12-16 22:13
@Tobrek I can't reproduce the error. Can you provide a shell script to reproduce this error without using nginx?

**Comment by lezh** [comment] 2021-12-17 01:33
Can you try [v0.39.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.39.1)?

**Comment by Tobrek** [comment] 2021-12-17 08:44
Good morning,
i can try to reproduce it with a script, but i don't know exactly what nginx is doing while checking the config.

Sry, v0.39.1 didn't work. Same problem.

**Comment by Tobrek** [comment] 2021-12-17 12:25
some additional information:
* I'm working with Debian 9 and 10 - the same problem at both systems.
* you have to use the file directly, every command using the directory will "solve" the problem. e.g. ls <file> didn't work, ls <dir> && ls <file> works. In my original case nginx is checking if some configured files exists.

Here a little script i wrote to test the behavior:
`#!/usr/bin/bash
bucket=				# bucket name
directory_in_bucket=	# directory in bucket for "only-dir" options
file_in_bucket=		# a file in the bucket directory to test
mountpoint=			# mountpoint

echo ""
echo "------------- cleanup"
fusermount -u $mountpoint && rm -rf $mountpoint

echo ""
echo "------------- create mountpoint and mounting"
mkdir -p $mountpoint
gcsfuse --only-dir $directory_in_bucket $bucket $mountpoint

echo ""
echo "------------- test ls <file> first time (NOT WORKING)"
ls -l $mountpoint/$file_in_bucket
echo "------------- test ls <file> X times again (NOT WORKING)"
ls -l $mountpoint/$file_in_bucket
ls -l $mountpoint/$file_in_bucket
ls -l $mountpoint/$file_in_bucket
ls -l $mountpoint/$file_in_bucket
echo "------------- test cat <file> (NOT WORKING)"
cat $mountpoint/$file_in_bucket

echo ""
echo "------------- ls mountpoint (works)"
ls -l $mountpoint
echo "------------- test ls <file> again (works)"
ls -l $mountpoint/$file_in_bucket

echo ""
echo "------------- cd mountpoint"
cd $mountpoint
echo "------------- test ls at directory (works)"
ls -l        
echo "------------- test ls <file> again (works)"
ls -l $file_in_bucket

echo ""
echo "------------- test cat <file> (works)"
cat $mountpoint/$file_in_bucket
`

output:
`------------- cleanup
fusermount: failed to unmount /tmp/test/tobrek: No such file or directory

------------- create mountpoint and mounting
2021/12/17 12:10:42.074475 Start gcsfuse/0.39.1 (Go version go1.17.5) for app "" using mount point: /tmp/test/tobrek
Added environment https_proxy: http://XXX.XXX.XXX.XXX:XXXX
2021/12/17 12:10:42.096706 Opening GCS connection...
2021/12/17 12:10:42.258742 Mounting file system "test-dir-in-bucket"...
2021/12/17 12:10:42.265707 File system has been successfully mounted.

------------- test ls <file> first time (NOT WORKING)
ls: cannot access '/tmp/test/tobrek/test-file.txt': No such file or directory
------------- test ls <file> X times again (NOT WORKING)
ls: cannot access '/tmp/test/tobrek/test-file.txt': No such file or directory
ls: cannot access '/tmp/test/tobrek/test-file.txt': No such file or directory
ls: cannot access '/tmp/test/tobrek/test-file.txt': No such file or directory
ls: cannot access '/tmp/test/tobrek/test-file.txt': No such file or directory
------------- test cat <file> (NOT WORKING)
cat: /tmp/test/tobrek/test-file.txt: No such file or directory

------------- ls mountpoint (works)
total 15
-rw-r--r-- 1 root root  692 May 25  2021 README
-rw-r--r-- 1 root root 1874 Nov 17 10:08 test-file.txt
-rw-r--r-- 1 root root 3750 Nov 17 10:08 file2.txt
-rw-r--r-- 1 root root 5624 Nov 17 10:08 file3.txt
-rw-r--r-- 1 root root 1675 Nov 17 10:08 file4.txt
------------- test ls <file> again (works)
-rw-r--r-- 1 root root 1874 Nov 17 10:08 /tmp/test/tobrek/test-file.txt

------------- cd mountpoint
------------- test ls at directory (works)
total 15
-rw-r--r-- 1 root root  692 May 25  2021 README
-rw-r--r-- 1 root root 1874 Nov 17 10:08 test-file.txt
-rw-r--r-- 1 root root 3750 Nov 17 10:08 file2.txt
-rw-r--r-- 1 root root 5624 Nov 17 10:08 file3.txt
-rw-r--r-- 1 root root 1675 Nov 17 10:08 file4.txt
------------- test ls <file> again (works)
-rw-r--r-- 1 root root 1874 Nov 17 10:08 test-file.txt

------------- test cat <file> (works)
my test file content`

**Comment by mariogits** [comment] 2021-12-19 08:39
Same issue happens to me with 0.39.1 when I am mounting the bucket with `--stat-cache-ttl 0 --type-cache-ttl 0`, without these 2 flags it can be mounted well. I downgraded to version 0.38.0 and everything works well again.

**Comment by jeunii** [comment] 2021-12-20 19:39
I have an issue thats working with `0.38.0` and failing with `0.39.1`

I have a pod that mounts a GCS bucket. That pod runs a script and copies files ( needs to overwrite files ) that resides on GCS. 

With `0.38.0`

```
k exec -it cvd-updater-gjtjn bash

root@cvd-updater-gjtjn:~# cp -rf /tmp/cvd-db/* /data/
root@cvd-updater-gjtjn:~# echo $?
0
```

With `0.39.1`

```
cp -rf /tmp/cvd-db/* /data/
cp: cannot create regular file '/data/bytecode-333.cdiff': File exists
cp: cannot create regular file '/data/bytecode.cvd': File exists
cp: cannot create regular file '/data/daily-26393.cdiff': File exists
cp: cannot create regular file '/data/daily.cvd': File exists
cp: cannot create regular file '/data/dns.txt': File exists
cp: cannot create regular file '/data/main-62.cdiff': File exists
cp: cannot create regular file '/data/main.cvd': File exists
```

**Comment by lezh** [comment] 2021-12-20 22:58
Thanks for reporting this issue. I made another release [v0.39.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.39.2). Hope it's fixed now.

**Comment by denniseijpe** [comment] 2021-12-21 07:57
We also have a kubernetes pod which mounts a GCS bucket. In folders with a large number of files, we couldn't list and read the files.

v0.39.2 Fixes our issues.

**Comment by mariogits** [comment] 2021-12-21 12:12
Yeah, v0.39.2 fixed the issue for me too. Thanks

**Comment by lezh** [comment] 2021-12-21 21:10
Thanks for the verification.

**Closed by lezh** 2021-12-21 21:10 UTC
