### ISSUE TITLE
mount fails with file system subtypes set

### ISSUE THREAD

**Issue by mapi** [GoogleCloudPlatform/gcsfuse#116] opened 2015-08-14 12:38 UTC
This is work

```
mount -t gcsfuse -o rw,user my-bucket /mnt/mybucket
```

These are not work.

```
mount -t fuse -o rw,user gcsfuse#my-bucket /mnt/mybucket
mount -t fuse.gcsfuse -o rw,user my-bucket /mnt/mybucket
```

`mount` can use another way. but these command return gcsfuse error.
```
Error: gcsfuse takes exactly two arguments.

NAME:
   gcsfuse - Mount a GCS bucket locally

USAGE:
   gcsfuse [global options] bucket mountpoint

[snip]
```

I met this problem while using chef. 
Chef's mount function support fuse, but use `mount -t fuse -o rw,user gcsfuse#my-bucket /mnt/mybucket` idiom.

**Comment by jacobsa** [comment] 2015-08-14 21:33
Thanks for the report. I'm not familiar with Chef; can you provide a link?

**Comment by jacobsa** [comment] 2015-08-16 23:09
After some Googling, I assume your talking about [this](https://www.chef.io/) Chef. In particular, [here](https://docs.chef.io/resource_mount.html) are the docs on mounting.

Can you share your Chef configuration that is causing this problem? It seems like you must have provided the string `fuse` or `fuse.gcsfuse` somewhere. If you set `fstype` to `gcsfuse` it seems like this would just work?

**Comment by mapi** [comment] 2015-08-17 14:06
My small config is here.

```ruby
mount "/mnt/my-bucket" do
  device "gcsfuse#my-bucket"
  fstype "fuse"
  options "rw,user"
  action [:mount, :enable]
end
```

without `fstype "fuse"`, Chef check device "my-bucket" is exist.
This makes "Device my-bucket does not exist" error. (Chef's issue)

```ruby
mount "/mnt/my-bucket" do
  device "my-bucket"
  fstype "fuse.gcsfuse"  # also fstype "gcsfuse"
  options "rw,user"
  action [:mount, :enable]
end
```

Of course, Chef should skip the device check if fstype is `gcsfuse`. but there is already generic way to skip check.

And I found `man mount(8)` after this issue created.
> The  programs  mount  and  umount  support filesystem subtypes. The subtype is defined by a '.subtype' suffix.
> For example  'fuse.sshfs'.  It's recommended to use subtype notation rather than add any prefix to the mount source (for example 'sshfs#example.com' is deprecated).

support mount with subtypes improve compatibility.

**Comment by jacobsa** [comment] 2015-08-17 22:28
To confirm, I believe you're saying that the following doesn't work because Chef gets in the way:

```ruby
mount "/mnt/my-bucket" do
  device "my-bucket"
  fstype "gcsfuse"
  options "rw,user"
  action [:mount, :enable]
end
```

This _should_ work; `mount -t gcsfuse my-bucket /mnt/my-bucket` is totally valid. Have you reported the bug to Chef?

That said, it does make sense to ensure subtypes work, for the reasons described in torvalds/linux@79c0b2df79eb56fc71e54c75cd7fb3acf84370f9. I'll look into it.

**Comment by jacobsa** [comment] 2015-08-17 23:02
For the record, I can reproduce this on Ubuntu 15.04 with the following line in `/etc/fstab`:

    jacobsa-standard-asia /home/jacobsa/mp fuse.gcsfuse rw,noauto,user

**Comment by jacobsa** [comment] 2015-08-17 23:11
@mapi: Could you confirm that the following causes this to work for you?

    sudo ln -s /sbin/mount.gcsfuse /sbin/mount.fuse.gcsfuse

**Comment by mapi** [comment] 2015-08-18 10:06
On Debian 8.1(jessie)

after create symlink.

```mount -t fuse.gcsfuse -o rw,user my-bucket /mnt/mybucket```
This works fine.

```mount -t fuse -o rw,user gcsfuse#my-bucket /mnt/mybucket```
This return error.
```
Error: gcsfuse takes exactly two arguments.

NAME:
   gcsfuse - Mount a GCS bucket locally

USAGE:
   gcsfuse [global options] bucket mountpoint

VERSION:
   0.10.0 (commit 2cda84d)
[snip]
```

**Comment by jacobsa** [comment] 2015-08-18 23:12
Thanks. Right, I haven't added support for the deprecated version. Will make a release that adds support for the modern version soon.

**Comment by jacobsa** [comment] 2015-08-19 02:08
Thanks again for the report. This should be fixed as of v0.11.0. @mapi: Could you update and confirm?

**Closed by jacobsa** 2015-08-19 02:08 UTC

**Comment by mapi** [comment] 2015-08-20 08:57
:clap: great work. thank you.

**Comment by rshade** [comment] 2018-07-11 21:12
@mapi how did you get this to work via chef?
