### ISSUE TITLE
Does not work in Mac OS 10.11

### ISSUE THREAD

**Issue by davies** [GoogleCloudPlatform/gcsfuse#176] opened 2016-07-01 07:51 UTC
I'm using latest gcsfuse from homebrew in Mac OS 10.11, after mounted a bucket successfully, but the mount point can't be accessed:

```
$ df -h
davies-test     1.0P     0  1.0P   0% /cfs
davies@localhost:~$ ls /cfs
ls: cannot access '/cfs': No such file or directory
```

Had installed osxfuse 2.8.3. Could reproduce this on two Mac (10.11)

**Comment by davies** [comment] 2016-07-01 07:54
cc @jacobsa

**Comment by jacobsa** [comment] 2016-07-01 08:44
Could you please post more information? Your gcsfuse version, how you are mounting, etc. Everything that would be needed to reproduce the problem.

**Comment by jacobsa** [comment] 2016-07-13 03:35
Closing this because I don't have the necessary information to reproduce. gcsfuse appears to work fine for me on OS X 10.11.5.

**Closed by jacobsa** 2016-07-13 03:35 UTC

**Comment by davies** [comment] 2016-07-25 03:51
@jacobsa I'm using OS X 10.11.6, not sure the minor version matter or not.

Here are output:
```
davies@MacBook-Pro:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
davies-test     1.0P     0  1.0P   0% /gcs
davies@MacBook-Pro:~$ ls /gcs
ls: cannot access '/gcs': No such file or directory
```

When I issued `ls /gcs`, there was no logging from gcsfuse, that's weird. Here are some loggings after mounted:
```
Using mount point: /gcs
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
Mounting file system...
fuse_debug: Op 0x00000000        connection.go:395] <- init
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
File system has been successfully mounted.
fuse_debug: Op 0x00000000        connection.go:395] <- GetInodeAttributes (inode 1)
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000004        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000005        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000006        connection.go:395] <- StatFS
fuse_debug: Op 0x00000007        connection.go:395] <- StatFS
fuse_debug: Op 0x00000005        connection.go:474] -> OK ()
fuse_debug: Op 0x00000004        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000006        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000005        connection.go:395] <- StatFS
fuse_debug: Op 0x00000004        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000007        connection.go:474] -> OK ()
fuse_debug: Op 0x00000005        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000006        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000007        connection.go:395] <- OpenDir (inode 1)
fuse_debug: Op 0x00000004        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000006        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000007        connection.go:474] -> OK ()
fuse_debug: Op 0x00000005        connection.go:395] <- StatFS
fuse_debug: Op 0x00000004        connection.go:395] <- ReleaseDirHandle
fuse_debug: Op 0x00000005        connection.go:474] -> OK ()
fuse_debug: Op 0x00000004        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:395] <- GetInodeAttributes (inode 1)
fuse_debug: Op 0x00000000        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000006        connection.go:395] <- StatFS
fuse_debug: Op 0x00000006        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000007        connection.go:395] <- OpenDir (inode 1)
fuse_debug: Op 0x00000007        connection.go:474] -> OK ()
fuse_debug: Op 0x00000005        connection.go:395] <- StatFS
fuse_debug: Op 0x00000005        connection.go:474] -> OK ()
fuse_debug: Op 0x00000004        connection.go:395] <- LookUpInode (parent 1, name "DCIM")
fuse_debug: Op 0x00000004        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000000        connection.go:395] <- LookUpInode (parent 1, name ".Spotlight-V100")
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000006        connection.go:395] <- StatFS
fuse_debug: Op 0x00000006        connection.go:474] -> OK ()
fuse_debug: Op 0x00000001        connection.go:395] <- StatFS
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
fuse_debug: Op 0x00000000        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000007        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index")
fuse_debug: Op 0x00000007        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000005        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index_unless_rootfs")
fuse_debug: Op 0x00000004        connection.go:395] <- StatFS
fuse_debug: Op 0x00000004        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:395] <- StatFS
fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
fuse_debug: Op 0x00000003        connection.go:395] <- StatFS
fuse_debug: Op 0x00000003        connection.go:474] -> OK ()
fuse_debug: Op 0x00000005        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000006        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index")
fuse_debug: Op 0x00000006        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000001        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index_unless_rootfs")
fuse_debug: Op 0x00000001        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000000        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index")
fuse_debug: Op 0x00000000        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000007        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index_unless_rootfs")
fuse_debug: Op 0x00000007        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000004        connection.go:395] <- StatFS
fuse_debug: Op 0x00000004        connection.go:474] -> OK ()
fuse_debug: Op 0x00000002        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index")
fuse_debug: Op 0x00000002        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000003        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index_unless_rootfs")
fuse_debug: Op 0x00000003        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000005        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index")
fuse_debug: Op 0x00000005        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000006        connection.go:395] <- LookUpInode (parent 1, name ".metadata_never_index_unless_rootfs")
fuse_debug: Op 0x00000006        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000001        connection.go:395] <- GetInodeAttributes (inode 1)
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()

```

**Comment by davies** [comment] 2016-07-25 03:53
Just found the cause, because it's mounted as root, after switched to other users, it worked.

That's a weird bug :)
