### ISSUE TITLE
doesn't seem to work with application default credentials or workload identity

### ISSUE THREAD

**Issue by joshk0** [GoogleCloudPlatform/gcsfuse#353] opened 2019-09-20 04:18 UTC
When I try to use gcsfuse with application default credentials provided by [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), it doesn't start up:

```
# gcsfuse -o allow_other,nonempty     --dir-mode 777     --file-mode 666     --temp-dir /var/tmp     --foreground  --debug_http --debug_fuse --debug_gcs my-bucket /data/bucket
Using mount point: /data/sftp
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
gcs: 2019/09/20 04:05:33.037114 Req              0x0: <- ListObjects()
http: ========== REQUEST:
GET http://www.googleapis.com/storage/v1/b/my-bucket/o?maxResults=1&projection=full HTTP/1.1
Host: www.googleapis.com
User-Agent: gcsfuse/0.0
Authorization: Bearer ya29.d.KrcBiQdGnWZCn1lzihkYqVzxum77TlJBibOZjRGo-5nFldj5hVuenvgeTSVFFlFi9j_J-rA7KbuJViu2FzLcVY2Gk_oXNIuSSikWmpkWJ2oeWgdNZSlJR7gkXGJBiRNfLuae56W8HkTcyzBG1dsG_frYtmbhjRbBO2fD_Oc65sATMfAInD30NcB3SpZSlOvLz_s3So9uroahcX82LVhu2CljLthLXhrbbnkqtAzDJKSoMl2xCiz8l6o4
Accept-Encoding: gzip

http: ========== RESPONSE:
HTTP/2.0 401 Unauthorized
Content-Length: 285
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json; charset=UTF-8
Date: Fri, 20 Sep 2019 04:05:33 GMT
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: UploadServer
Vary: Origin
Vary: X-Origin
Www-Authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token
X-Guploader-Uploadid: AEnB2UrhNp9R58FxJ2-K4DuOvhGbjxz8BIUrhCnMFE1th9rcjM8RPP_3jeULF0w__d9c9jlWqFDfscJnViTf_VCf88TVKXDS2TVqxWlx8540-yPOrtJAHyk

{
  "error": {
    "code": 401,
    "message": "Invalid Credentials",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
http: ====================
gcs: 2019/09/20 04:05:33.238565 Req              0x0: -> ListObjects() (201.470491ms): googleapi: Error 401: Invalid Credentials, authError
gcs: 2019/09/20 04:05:33.238816 Req              0x1: <- ListObjects()
http: ========== REQUEST:
GET http://www.googleapis.com/storage/v1/b/my-bucket/o?maxResults=1&projection=full HTTP/1.1
Host: www.googleapis.com
User-Agent: gcsfuse/0.0
Authorization: Bearer ya29.d.KrcBiQdGnWZCn1lzihkYqVzxum77TlJBibOZjRGo-5nFldj5hVuenvgeTSVFFlFi9j_J-rA7KbuJViu2FzLcVY2Gk_oXNIuSSikWmpkWJ2oeWgdNZSlJR7gkXGJBiRNfLuae56W8HkTcyzBG1dsG_frYtmbhjRbBO2fD_Oc65sATMfAInD30NcB3SpZSlOvLz_s3So9uroahcX82LVhu2CljLthLXhrbbnkqtAzDJKSoMl2xCiz8l6o4
Accept-Encoding: gzip

http: ========== RESPONSE:
HTTP/2.0 401 Unauthorized
Content-Length: 249
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Fri, 20 Sep 2019 04:05:33 GMT
Expires: Fri, 20 Sep 2019 04:05:33 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin
Www-Authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token
X-Guploader-Uploadid: redacted

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
http: ====================
gcs: 2019/09/20 04:05:33.253866 Req              0x1: -> ListObjects() (15.043334ms): googleapi: Error 401: Invalid Credentials, authError
WARNING, bucket doesn't appear to work:  googleapi: Error 401: Invalid Credentials, authError
Mounting file system...
fuse_debug: 2019/09/20 04:05:33.256115 Op 0x00000001        connection.go:396] <- init
fuse_debug: 2019/09/20 04:05:33.256212 Op 0x00000001        connection.go:479] -> OK ()
File system has been successfully mounted.
```

I verified that Workload Identity is otherwise working by going thru the motions described in the guide. By creating a pod that has the same service account as my gcsfuse pod, i was able to `gsutil ls` the bucket i want to use with gcsfuse, so that's why I'm more incliend to think it's a gcsfuse problem.

**Comment by samos123** [comment] 2021-02-04 06:14
I just used workload identity with GKE and was able to use gcsfuse succesfully. I'm unable to reproduce this issue with latest release of gcsfuse. Is your pod using hostNetwork? if yes then that won't work. I had to stop using hostNetwork: true to get workload identity to work.

**Comment by marrau** [comment] 2021-07-16 09:16
Hi, just want to confirm @samos123 oberservations. 

Whatever i did with csi-gcs (different parameters, uid, gid, dir-mode, file-mode, ....) resulted in a sometimes working empty dir, with no option to successfully write data and more often than wanted, in "permission denied" (service account is correct, permission is set, scope is storage-full). So i couldn´t find out what the problem was.

Setting the "hostNetwork: false" does the trick. Just changed that and made sure everything could remount - and it´s working.

**Comment by avidullu** [comment] 2022-04-14 07:26
Thanks @samos123 for the useful tip here. Closing this out since the issue has a solution.

**Closed by avidullu** 2022-04-14 07:26 UTC
