### ISSUE TITLE
panic: interface conversion: inode.Inode is nil, not *inode.FileInode

### ISSUE THREAD

**Issue by joshk0** [GoogleCloudPlatform/gcsfuse#164] opened 2016-03-07 19:58 UTC
We have a sftp server hooked up to gcsfuse 0.17.0. Recently, a user was able to make it panic. It seems that the user was uploading files and gcsfuse crashed right after a StatObject call. Our log times aren't super accurate, but it looks like all this happened within about 5 seconds. Let me know what other data I can provide which might help here. Obviously, we don't have accurate repro steps, but have some plans to increase sftp's internal logging so we can see what the user was doing to cause the crash. Knee jerk reaction, it looks like a race condition or stale cache of some sort.

```
sshd: Accepted password for some_user from 10.60.3.1 port 50541 ssh2#015
sshd: pam_unix(sshd:session): session opened for user some_user by (uid=0)
sshd: pam_env(sshd:session): Unable to open env file: /etc/default/locale: No such file or directory
gcsfuse: gcs: Req            0x2be: <- StatObject("some_user/foobar_20160304.csv/")
gcsfuse: gcs: Req            0x2bf: <- StatObject("some_user/foobar_20160304.csv")
gcsfuse: gcs: Req            0x2be: -> StatObject("some_user/foobar_20160304.csv/") (25.132669ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcsfuse: gcs: Req            0x2bf: -> StatObject("some_user/foobar_20160304.csv") (140.249602ms): OK 
gcsfuse: gcs: Req            0x2c0: <- UpdateObject("some_user/foobar_20160304.csv")
gcsfuse: gcs: Req            0x2c0: -> UpdateObject("some_user/foobar_20160304.csv") (213.891389ms): OK 
gcsfuse: gcs: Req            0x2c1: <- Read("some_user/foobar_20160304.csv", <nil>)
gcsfuse: gcs: Req            0x2c1: -> Read("some_user/foobar_20160304.csv", <nil>) (1.078678466s): OK 
gcsfuse: gcs: Req            0x2c2: <- CreateObject("some_user/foobar_20160304.csv")
gcsfuse: gcs: Req            0x2c2: -> CreateObject("some_user/foobar_20160304.csv") (1.93310676s): OK 
sshd: Received disconnect from 10.60.3.1: 11: disconnected by user#015
sshd: pam_unix(sshd:session): session closed for user some_user
sshd: Accepted password for some_user from 10.240.0.16 port 50542 ssh2#015
sshd: pam_unix(sshd:session): session opened for user some_user by (uid=0)
sshd: pam_env(sshd:session): Unable to open env file: /etc/default/locale: No such file or directory
gcsfuse: gcs: Req            0x2c3: <- StatObject("some_user/other_data_20160304.csv/")
gcsfuse: gcs: Req            0x2c4: <- StatObject("some_user/other_data_20160304.csv")
gcsfuse: gcs: Req            0x2c3: -> StatObject("some_user/other_data_20160304.csv/") (26.681731ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcsfuse: gcs: Req            0x2c4: -> StatObject("some_user/other_data_20160304.csv") (59.193025ms): OK
gcsfuse: panic: interface conversion: inode.Inode is nil, not *inode.FileInode
gcsfuse: 
gcsfuse: goroutine 32640 [running]:
gcsfuse: panic(0x8f6200, 0xc8200d5a80)
gcsfuse: #011/home/jacobsa/clients/go/src/runtime/panic.go:464 +0x3e6
gcsfuse: github.com/googlecloudplatform/gcsfuse/internal/fs.(*fileSystem).OpenFile(0xc8204f6300, 0x7efd8bd17c60, 0xc820a06060, 0xc820c659a0, 0x0, 0x0)
gcsfuse: #011/tmp/build_gcsfuse_gopath620360990/src/github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:1471 +0x1d2
gcsfuse: github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc82044ca80, 0xc8201938c0, 0x7efd8bd17c60, 0xc820a06060, 0x7f5c80, 0xc820c659a0)
gcsfuse: #011/tmp/build_gcsfuse_gopath620360990/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:170 +0x9d2
gcsfuse: created by github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
gcsfuse: #011/tmp/build_gcsfuse_gopath620360990/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:108 +0x18f
sshd: Received disconnect from 10.240.0.16: 11: disconnected by user#015
sshd: pam_unix(sshd:session): session closed for user some_user
```

**Comment by jacobsa** [comment] 2016-03-07 23:11
Which version are you running (`gcsfuse -v`)?

**Comment by jacobsa** [comment] 2016-03-08 08:29
Also, it looks like you were running with `--debug_gcs` (correct?). It would be most helpful if you were able to get output with `--debug_fuse`.

Assuming you're running 0.17.0, the panic happened [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/v0.17.0/internal/fs/fs.go#L1471). It doesn't look like there's any subtle timing things going on here—it appears the kernel asked to open an inode number that we don't know about. That's really weird, and I'd love to have `--debug_fuse` output if you can make this happen again...

**Comment by jacobsa** [comment] 2016-03-08 08:31
Oh, and `--debug_invariants` would be even more helpful to catch errors early, assuming you can deal with any performance hit it causes.

**Comment by joshk0** [comment] 2016-03-08 15:33
Cool. --debug_invariants isn't great for us if it'll crash more often and be slower. The performance hit is also a concern because this is used for a customer facing requirement. Will --debug_fuse significantly impact performance?

**Comment by jacobsa** [comment] 2016-03-08 21:37
`--debug_invariants` will only crash if something is seriously wrong (as in your original reported case). This would likely lead to a crash eventually anyway, but crashing early makes it clear where the problem started. I don't know whether you will notice the performance difference or not.

`--debug_fuse` prints a lot of lines, but again you'd have to try it to see if the load is significant compared to the rest of what you're doing.

**Comment by jacobsa** [comment] 2016-03-08 21:38
Also, can you confirm the version you're running?

**Comment by joshk0** [comment] 2016-03-09 16:26
Yes, it was 0.17.0. Sorry - had ninja-edited the OP so thought I had provided that info already.

We'll give both of these a shot. Thanks, and will report back

**Comment by jacobsa** [comment] 2016-05-18 20:47
Hi @joshk0, any luck with this?

**Comment by jacobsa** [comment] 2016-05-18 20:47
(It's possible this is the same issue as #170; debug logs from 0.17.2 would help confirm it.)

**Comment by jacobsa** [comment] 2016-05-23 11:44
Calling this a dupe of #170.

**Closed by jacobsa** 2016-05-23 11:44 UTC
