### ISSUE TITLE
Fuse not installing (centos7)

### ISSUE THREAD

**Issue by klj613** [GoogleCloudPlatform/gcsfuse#667] opened 2022-04-28 14:59 UTC
Following the process on https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#other-distributions to install fuse via the yum repository results in the installation failing.

```
[root@www vagrant]# sudo yum install gcsfuse
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.centos.org
 * extras: mirror.centos.org
 * updates: mirror.centos.org
gcsfuse                                                                                                                                 | 1.4 kB  00:00:00     
gcsfuse/primary                                                                                                                         | 1.9 kB  00:00:01     
gcsfuse                                                                                                                                                    9/9
Resolving Dependencies
--> Running transaction check
---> Package gcsfuse.x86_64 0:0.41.0-1 will be installed
--> Processing Dependency: fuse for package: gcsfuse-0.41.0-1.x86_64
--> Running transaction check
---> Package fuse.x86_64 0:2.9.2-11.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================================
 Package                              Arch                                Version                                   Repository                            Size
===============================================================================================================================================================
Installing:
 gcsfuse                              x86_64                              0.41.0-1                                  gcsfuse                               11 M
Installing for dependencies:
 fuse                                 x86_64                              2.9.2-11.el7                              base                                  86 k

Transaction Summary
===============================================================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 11 M
Installed size: 26 M
Is this ok [y/d/N]: y
Downloading packages:
(1/2): fuse-2.9.2-11.el7.x86_64.rpm                                                                                                     |  86 kB  00:00:00     
warning: /var/cache/yum/x86_64/7/gcsfuse/packages/69d80be1f6eb951b18ce00d79fa5d93c0c8ba64221ee3a1e9239578d48cb0cfd-gcsfuse-0.41.0-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 5f6eee39: NOKEY
Public key for 69d80be1f6eb951b18ce00d79fa5d93c0c8ba64221ee3a1e9239578d48cb0cfd-gcsfuse-0.41.0-1.x86_64.rpm is not installed
(2/2): 69d80be1f6eb951b18ce00d79fa5d93c0c8ba64221ee3a1e9239578d48cb0cfd-gcsfuse-0.41.0-1.x86_64.rpm                                     |  11 MB  00:00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                           11 MB/s |  11 MB  00:00:00     
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x0B5FC9E2:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: 9c5a 47a0 dedd 6927 121f 9095 daff b062 0b5f c9e2
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Importing GPG key 0x307EA071:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)"
 Fingerprint: 7f92 e05b 3109 3bef 5a3c 2d38 feea 9169 307e a071
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Importing GPG key 0x836F4BEB:
 Userid     : "gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>"
 Fingerprint: 59fe 0256 8272 69dc 8157 8f92 8b57 c5c2 836f 4beb
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
Importing GPG key 0x3E1BA8D5:
 Userid     : "Google Cloud Packages RPM Signing Key <gc-team@google.com>"
 Fingerprint: 3749 e1ba 95a8 6ce0 5454 6ed2 f09c 394c 3e1b a8d5
 From       : https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
Is this ok [y/N]: y


Public key for 69d80be1f6eb951b18ce00d79fa5d93c0c8ba64221ee3a1e9239578d48cb0cfd-gcsfuse-0.41.0-1.x86_64.rpm is not installed


 Failing package is: gcsfuse-0.41.0-1.x86_64
 GPG Keys are configured as: https://packages.cloud.google.com/yum/doc/yum-key.gpg, https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

I've had a look around and attempted several times to no avail. This was attempted on a fresh CentOS 7 virtual machine

**Comment by mliljedahl** [comment] 2022-04-28 16:15
Can confirm that the issue is also on CentOS 8 :+1:

**Comment by vadlakondaswetha** [comment] 2022-04-28 17:13
Can you try with the latest version v0.41.1

**Comment by klj613** [comment] 2022-04-29 09:46
I can also confirm gcsfuse-0.41.1-1.x86_64 works :+1: Thanks :)

**Comment by avidullu** [comment] 2022-05-02 05:20
Thanks a lot for the inputs here. Closing this out.

**Closed by avidullu** 2022-05-02 05:20 UTC
