### ISSUE TITLE
Input/output error (5)

### ISSUE THREAD

**Issue by kernelt** [GoogleCloudPlatform/gcsfuse#126] opened 2015-09-07 19:20 UTC
Hi Aaron. We have a new issue. I tried to copy a lot of files and dirs (~40k objects) from a local dir to a bucket-dir, but in all cases I had many interrupted process of copying following with errors:
```
rsync: ftruncate failed on "/bucket/my/r_p.cpp": Input/output error (5)
```
I tried to use that options of rsync
```
-r -av --delete --inplace --no-times --no-perms --ignore-errors
```
But it doesn't help. A standard "cp" linux command doesn't help too.
In all cases (rsync, cp), the process of copying files and dirs interrupts with "Input/output error". Also, with the "cp" command, many files copying with "a zero size".
What it may be?

**Comment by jacobsa** [comment] 2015-09-07 22:48
"Input/output error" is `EIO`, which is what gcsfuse translates arbitrary errors e.g. talking to GCS as. What does gcsfuse print on stderr when this happens? Are you able to reproduce it reliably?

**Comment by jacobsa** [comment] 2015-09-08 23:10
Closing this since I don't see an action I can take. If you find out what's causing the `EIO`, please let me know.

**Closed by jacobsa** 2015-09-08 23:10 UTC
