### ISSUE TITLE
Feature Request: --pre-create-implicit-dirs

### ISSUE THREAD

**Issue by avloss** [GoogleCloudPlatform/gcsfuse#1748] opened 2024-02-27 16:45 UTC
Please add an option to "pre-create-implicit-dirs". We just wan to have "filesystem-like" experience.

**Comment by gargnitingoogle** [comment] 2024-02-28 06:56
@avloss thanks for suggesting. 

I have taken this as a feature request for the team. We'll evaluate it and put it in our roadmap accordingly.

I am also reducing priority to P2 as this is not a blocking issue.

**Comment by gargnitingoogle** [comment] 2024-02-28 21:28
@avloss I just wanted to add that this request is a duplicate of https://github.com/GoogleCloudPlatform/gcsfuse/issues/1387 . Anther user had once shared a [script](https://github.com/GoogleCloudPlatform/gcsfuse/issues/1387#issuecomment-1730738221) that they had written to do this manually. You may want to give it a try, but it not verified by the gcsfuse team, so please avoid it for production workloads.

**Comment by gargnitingoogle** [comment] 2024-02-28 21:35
Marking this closed as this is now a tracked feature request.

**Closed by gargnitingoogle** 2024-02-28 21:35 UTC
Labels: feature request, p2

**Comment by avloss** [comment] 2024-02-29 09:49
Thank you for your swift response. Please keep the great work on these amazing tools that make our life as developers so much easier! :)

**Comment by marcoa6** [comment] 2024-04-11 18:45
#1748
