### ISSUE TITLE
gcsfuse keeps losing connection

### ISSUE THREAD

**Issue by wilchak** [GoogleCloudPlatform/gcsfuse#204] opened 2017-01-03 19:28 UTC
After a couple of days, when I try to cd into my mount point directory, I get the error message: "Transport endpoint is not connected". When it gets into this stuck place, it cannot be unmounted. The only way to fix things is to reboot the machine.

The machine in question is a GCE VM. Everything else works fine, other than it disconnecting like this. Please let me know if I can supply any logs, or how I can help triage this issue.

Thanks.

**Comment by jacobsa** [comment] 2017-01-03 22:39
This sounds like the gcsfuse process has died. Please use `--foreground` and maybe `--debug_fuse` and capture stderr to figure out what's going on.

**Comment by wilchak** [comment] 2017-01-05 16:47
Doing this now. I'll post the results when I catch it disconnecting.

**Comment by PhilBrammer** [comment] 2017-02-06 14:32
I am seeing the same behavior on a GCE instance (debian-8-jessie-v20170124, central1-c) mounted (gcsfuse 0.20.1) to a multi-region (US) storage bucket.  Although in my case, I can simply re-execute the gcsfuse command and it hooks back up.  I don't need to reboot.  

I am going to let it run with --foreground redirecting stderr to a file and see if I can capture it next time it happens.  I do not have a repro yet or even a pattern of how often this happens.

**Comment by jacobsa** [comment] 2017-03-16 21:53
Closing this. Please re-open if you can obtain some debugging info that implies it's a gcsfuse bug.

**Comment by jeffrobins** [comment] 2017-05-11 07:18
I have what looks like a memory leak to me.  I mounted my bucket on a google compute engine and used rsync to copy files from my home server to the mounted bucket.  

1st run with mariadb stopped:
Early in the process gcsfuse was using about 3% of the RAM (19MiB).  I used "top" to monitor the memory usage.  I also watched the free memory go down using "free -m".  I normally have the mariandb server running, but I shut it down for this run.

As the process continued, that grew to 48.2% (290MiB).  When I stopped rsync, the rise in memory usage seemed to stop, but didn't shrink.  CPU usage from gscfuse did drop to 0.0%.  When I unmounted the bucket, the memory was finally freed.  CPU usage by gcsfuse always remained low (<1%). rsync never went above 0.3% of the RAM.

2nd run with mariadb running:
mariadb takes up 13.9% of the memory. gcsfuse came up with 1.8% to start with and got up to 4.7% before rsync began to copy files.  gcsfuse got up around 45% of memory and then self terminated.  "mount" still thinks the bucket is mounted, but "ls" in the parent folder of the bucket reports "Transport endpoint is not connected".  I have attached the end of my log from running "gcsfuse --foreground --debug_fuse <bucket_name> /mnt/cloud/ &>fuse_log2 &", but it ends without an error.
[fuse_log2.txt](https://github.com/GoogleCloudPlatform/gcsfuse/files/992118/fuse_log2.txt)

**Comment by jacobsa** [comment] 2017-05-12 03:09
@jeffrobins: could you please open a separate issue about memory usage? (It's possible that you're just seeing the default Go behavior of allowing for 100% growth of the heap before garbage collecting. You can test this theory by manipulating [`GOGC`](https://golang.org/pkg/runtime/).)

I've reopened the bug, but there's not really anything actionable here. How confident are you that you've captured all of stderr? Are you able to get an exit code? Is it possible something on your system killed gcsfuse?

**Comment by jeffrobins** [comment] 2017-05-12 03:19
@jacobsa I will open another ticket, but I figure I'll reply to you here as well.

According to https://askubuntu.com/questions/625224/how-to-redirect-stderr-to-a-file the command I ran would redirect stdout and strderr to file fuse_log2.

After your question, I ran "dmesg", which provided the following:
[41300.374311] Out of memory: Kill process 22947 (gcsfuse) score 439 or sacrifice child
[41300.382272] Killed process 22947 (gcsfuse) total-vm:655584kB, anon-rss:264388kB, file-rss:0kB, shmem-rss:0kB

I'm not sure what killed gcsfuse (systemd, kernel?).  I'll look into manipulating GOGC next.

**Comment by jacobsa** [comment] 2017-08-09 02:30
Closing due to lack of activity. If there's still something actionable here please let me know.

**Closed by jacobsa** 2017-08-09 02:30 UTC

**Comment by j3pic** [comment] 2020-12-01 00:11
I'm running into this problem in Google Cloud Composer, where the Airflow workers are set up by Google to use gcsfuse. It renders Composer utterly unreliable (on top of other sources of Airflow unreliability), since this problem can happen right in the middle of a DAG run, the gcsfuse filesystem is where the logs go, and processes just pause, apparently forever, once the gcsfuse connection is dropped. I don't see where gcsfuse is invoked in any script I could find within an Airflow worker. Looks like the problem is wholly internal to Google. If you guys look for instances of this problem within your infrastructure, you'll find them.

**Comment by VengefulAncient** [comment] 2020-12-18 08:31
We have just ran into this exact problem on GKE where one of our deployments is using `gcsfuse` to upload images to a GCS bucket. Pod memory limit not reached, pod not OOM-killed, pod continues working, just with a dead `gcsfuse` process and a broken bucket connection. Matching memory usage graph (see attached screenshot) and log errors showed that the sharp drop in memory usage coincides with `gcsfuse` process dying.
![image](https://user-images.githubusercontent.com/11550576/102592126-e5f6c300-4177-11eb-8c71-d440871394c3.png)

**Comment by raj-prince** [comment] 2023-10-30 11:31
@suvashishtha Are you experiencing gcsfuse related issues with the latest Cloud Composer setup?

 If so, please create an new issue with more detailed information so that either the GCSFuse team or the Google Cloud Composer team can investigate.

Thanks!
