### ISSUE TITLE
mounting buckets hanging with gcsfuse 0.42.1

### ISSUE THREAD

**Issue by ledmil01** [GoogleCloudPlatform/gcsfuse#985] opened 2023-03-02 16:00 UTC
**Describe the bug**
We have been using gcsfuse for a few years to mount 4 gcs buckets used by the system.  The instance is built on demand and uses the latest CentOS 7 build.  Cloud logging showed the first attempt to mount and nothing further from that instance:

startup-script: 2023/03/01 02:18:28.659437 Opening GCS connection...

Several other test attempts have been made to retry and these resulted in the same outcome.

Having noticed the release of 0.42.1 in the last day and the previous working attempt was using 0.41.12 we modified the Deployment Manager template to force install of 0.41.12 (changed the install command in start-up script to "yum install -y gcsfuse-0.41.12") to and tests of the process are now successful

**To Collect more Debug logs**
Build CentOS 7 instance with latest family image managed by Google
Install fuse 0.42.1
mount bucket with (note command modified as this is from a parameterised template):
gcsfuse -o allow_other --file-mode=777 --dir-mode=777 <bucket name> /mnt/<bucket directory>

**System (please complete the following information):**
 - OS: CentOS 7
 - Platform GCP compute instance
 - Version 0.42.1

**Comment by arpanda** [comment] 2023-03-02 21:08
I am also having the same issue in google colab. It was working last week. The issue is may be due to Verison 0.42.1. 

Steps I did

1. Install gcsfuse

```
!echo "deb http://packages.cloud.google.com/apt gcsfuse-bionic main" > /etc/apt/sources.list.d/gcsfuse.list
!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - 
!apt -qq update
!apt -qq install gcsfuse
```
2. verification code to authenticate yourself.
```
from google.colab import auth
auth.authenticate_user()
```

3. Create and mount directory
```
!mkdir colab_direcoty
!gcsfuse --implicit-dirs data_lab2023 colab_direcoty
```

Here is the error while running `gcsfuse --implicit-dirs` command
```red
2023/03/02 20:24:46.950768 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /content/colab_direcoty
2023/03/02 20:24:46.972087 Opening GCS connection...
daemonize.Run: readFromProcess: Decode: EOF
```

**Comment by danking** [comment] 2023-03-02 22:41
I suspect this is related to https://github.com/GoogleCloudPlatform/gcsfuse/issues/982

Maybe error messages are getting muffled on your end? One other short term fix is to add storage.buckets.get permission to the account in question.

**Comment by ledmil01** [comment] 2023-03-03 00:27
> I suspect this is related to #982
> 
> Maybe error messages are getting muffled on your end? One other short term fix is to add storage.buckets.get permission to the account in question.

To confirm, the service account used for compute has storage.buckets.get permission from a role configured at the project level, so would be hard to see that as being the issue

**Comment by Tulsishah** [comment] 2023-03-03 06:27
For now, you can pass the enable-storage-client-library=false flag in the latest version. Currently, We are looking into it. We will let you know once it gets fixed.

**Comment by vadirajks** [comment] 2023-03-03 06:50
it scared up production pretty badly

**Comment by ledmil01** [comment] 2023-03-03 08:58
> For now, you can pass the enable-storage-client-library=false flag in the latest version. Currently, We are looking into it. We will let you know once it gets fixed.

Hello, thanks for the reply, will test this today.  Have been through the docs and a web search but can't find any information about operational changes this flag will bring, does anyone have any experience with any issues of reliability or performance?

Did see in the flags.go file that setting this to false uses jacobsa/gcloud (guessing that refers to:  https://github.com/jacobsa/gcloud)) in place of the go storage client library, but can't find information about what difference that makes from a consumer of gcsfuse perspective

**Comment by Tulsishah** [comment] 2023-03-06 12:33
Hi @ledmil01, I replicate the issue by the given details, and I am getting this error mountWithArgs: mountWithConn: fs.NewServer: create the file system: SetUpBucket: OpenBucket: googleapi: Error 403: username -serviceaccount.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden

It does not hang in my case. Did you face this type of issue anytime?

**Comment by raj-prince** [comment] 2023-03-10 11:01
Hi @arpanda, @ledmil01, @ibamcarousell, @AviMoto,

We are still not sure, this issue is same as https://github.com/GoogleCloudPlatform/gcsfuse/issues/982. Every time we tried, we get the proper error message - permission denied, but not in this case. Could you please help in providing the logs for this issue? I'll appreciate a lot for this.

Please use --foreground, --debug_gcs, --debug_fuse, --debug_http flags while mounting gcsfuse to get the logs.

Thanks a lot!!
Prince.

**Comment by gauee** [comment] 2023-03-10 13:22
Hi,
I am facing the same problem, below is my log output.

```
-sh-4.2$ gcsfuse --debug_fuse --debug_gcs --debug_http --debug_invariants --implicit-dirs core-bucket /apps/core_dumps
2023/03/10 13:04:25.944805 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /apps/core_dumps
2023/03/10 13:04:25.968790 Opening GCS connection...
daemonize.Run: readFromProcess: Decode: EOF
-sh-4.2$ sudo -S -u jboss gcsfuse --debug_fuse --debug_gcs --debug_http --debug_invariants --foreground --implicit-dirs core-bucket /apps/core_dumps
2023/03/10 13:05:20.125782 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /apps/core_dumps
2023/03/10 13:05:20.125927 Opening GCS connection...
2023/03/10 13:05:20.131598 Creating a mount at "/apps/core_dumps"
2023/03/10 13:05:20.132509 Creating a new server...
2023/03/10 13:05:20.132545 Set up root directory for bucket core-bucket
gcs: 2023/03/10 13:05:20.221970 Req              0x0: <- ListObjects("")
gcs: 2023/03/10 13:05:20.270429 Req              0x0: -> ListObjects("") (48.455632ms): OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa889ff]

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.convertACLRuleToObjectAccessControl(...)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:48
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.ObjectAttrsToBucketObject(0xc000972000)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:58 +0x5ff
github.com/googlecloudplatform/gcsfuse/internal/storage.(*bucketHandle).ListObjects(0xc0002acb10, {0x11648d0, 0xc00003c158}, 0xc00009b6d0)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/bucket_handle.go:245 +0x2aa
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs.(*debugBucket).ListObjects(0xc0000792a0, {0x11648d0, 0xc00003c158}, 0xc00009b6d0)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go:207 +0x16b
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching.(*fastStatBucket).ListObjects(0xc000485040, {0x11648d0?, 0xc00003c158?}, 0xc000745101?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go:219 +0x34
github.com/googlecloudplatform/gcsfuse/internal/gcsx.(*bucketManager).SetUpBucket(0xc0002d0360, {0x11648d0, 0xc00003c158}, {0x7ffd7cf8e823?, 0x80?})
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:248 +0x5c4
github.com/googlecloudplatform/gcsfuse/internal/fs.NewFileSystem({0x11648d0, 0xc00003c158}, 0xc00059f5e8)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:167 +0x47a
github.com/googlecloudplatform/gcsfuse/internal/fs.NewServer({0x11648d0?, 0xc00003c158?}, 0xc0007455e8)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/server.go:28 +0x2f
main.mountWithConn({0x11648d0, 0xc00003c158}, {0x7ffd7cf8e823, 0x29}, {0x7ffd7cf8e84d, 0x10}, 0xc0003b2840, 0x50?, {0x1159d80, 0xc000014598}, ...)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/mount.go:122 +0x4ba
main.mountWithArgs({0x7ffd7cf8e823, 0x29}, {0x7ffd7cf8e84d, 0x10}, 0xc0003b2840, 0x6?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:205 +0x2d2
main.runCLIApp(0xc00053f8f8?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:369 +0xf25
main.run.func1(0x1?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:404 +0x25
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction({0xcd6640?, 0xc0000923f0?}, 0xc00047ec40?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:526 +0x50
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc00047ec40, {0xc000036090, 0x9, 0x9})
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:286 +0x7ca
main.run()
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xcb
main.main()
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:426 +0x4a
-sh-4.2$
```

**Comment by gauee** [comment] 2023-03-10 14:29
Thank you @raj-prince ! once added flag I was able to mount bucket.

**Comment by sethiay** [comment] 2023-03-17 07:31
The fix for this issue has been released in the latest GCSFuse release i.e. [v0.42.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.42.2). With GCSFuse v0.42.2, you can skip passing --enable-storage-client-library=false flag.
Marking this issue as closed. Please feel free to re-open in case you face the same issue again.

Thanks for your patience !

**Closed by sethiay** 2023-03-17 07:31 UTC
Labels: bug, next release
