### ISSUE TITLE
Duplicate files are generating suddenly when doing sftp on Linux dir - GCSFuse

### ISSUE THREAD

**Issue by captain-naresh** [GoogleCloudPlatform/gcsfuse#461] opened 2020-11-18 14:30 UTC
Issue - when doing sftp , duplicate files are generating in GCP storage bucket which is connected to pub sub.(you can not see 2 files as same files will be updating in bucket again , so pub sub will be having two files.)

syntax - 
bucket-name  /home/${user} gcsfuse rw,_netdev,allow_other,nonempty,uid=${uid},gid=${gid},only_dir=${user})

**Comment by lezh** [comment] 2020-12-01 06:35
Can you provide more info?
1. The version of gcsfuse
2. The version of the OS
3. How did you mount gcsfuse
4. How did you access gcsfuse when it's mounted
5. What was the actual behavior of it
6. What was the expected behavior of it

**Comment by captain-naresh** [comment] 2020-12-01 10:32
The version of gcsfuse - **gcsfuse-el7-x86_64**
The version of the OS - **centos-8**
How did you mount gcsfuse - **via fstab** 
How did you access gcsfuse when it's mounted - 
**via fstab entry - 
bucket  /home/${user} gcsfuse rw,_netdev,allow_other,nonempty,uid=${uid},gid=${gid},only_dir=${user}**
What was the actual behavior of it - 
**Actually 1 file is being placed in sftp server path, gcsfuse mounted that file to bucket and from bucket when Cloud Function picks up the file it picks up twice. because gcsfuse will place the file first then complete it with actual contents and complete the file(as what i think).**

What was the expected behavior of it - 
**Sftp files to Linux box, then via gcsfuse, files will be mounted to bucket, then on bucket we have cloud function event listener as which have finalize event.** , So if 1 file is being sftp then through out cloud function , only 1 file will be process out.

**Comment by mattkizaric-leveragelab** [comment] 2021-04-09 17:44
I am also dealing with this issue, @captain-naresh did you find a work around for this?

**Comment by bjornleffler** [comment] 2021-04-09 21:24
GCS Fuse should send two notifications per new file. First a notification that an empty file has been created, and a second notification when the content has been written and finalised.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#pubsub-notifications-on-file-creation

Is sftp creating two files, as in a temporary file first, and then the final file?

**Comment by captain-naresh** [comment] 2021-04-11 11:59
Yes @mattkizaric-leveragelab , In my case (GCSFUSE on Linux --> Bucket --> Cloud Function ), this duplicate file is desired behavior of GCSFUSE in bucket.
it only happened if you are placing new file through GCSFUSE in bucket so it create first file as empty and then fill it or replace it with contents so two times invocation happens for Cloud function. If you have already file there in bucket or sftp and you are renaming it, then it works fine; only one invocation.

We are dealing it with placing the first file with .tmp , then fill it with contents and then renaming it with original file extension and then discarding the .tmp file in Cloud function.

I hope this will help of your findings :)

**Comment by avidullu** [comment] 2022-04-14 09:17
Closing this out since it seems this is WAI and documented.
Please feel free to raise a new request or reopen this in case there is something more that needs to be done related to this.

**Closed by avidullu** 2022-04-14 09:17 UTC
