### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS doesn't work

### ISSUE THREAD

**Issue by molerus** [GoogleCloudPlatform/gcsfuse#177] opened 2016-07-07 21:13 UTC
It looks like process demonisation strips all env variables except for PATH and hence the child process cannot find it.

**Comment by JustDevNull** [comment] 2016-07-08 08:52
Try to add to your script the following env variables and see if in that way it runs without problems, in my case I had problems with gsutil in crontab because it was unable to find the credentials, but with this it worked :

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/share/google/google-cloud-sdk/bin/
HOME=/root
BOTO_CONFIG="/root/.config/gcloud/legacy_credentials/your_service_account/.boto"

Take in mind that in the PATH env I have "/usr/local/share/google/google-cloud-sdk/bin/" because of my installation config, and you can find the ".boto" with a simple :

find / -name ".boto"

I hope I did not misinterpreted what you wanted to say.

**Comment by molerus** [comment] 2016-07-08 09:19
I think your workflow follows different path of credential locations. You may look it up at
https://github.com/GoogleCloudPlatform/gcsfuse/blob/5d5f9c71a302725b302ced5cf2242b367d05739a/vendor/golang.org/x/oauth2/google/default.go#L62
I was following the instructions found on https://cloud.google.com/storage/docs/gcs-fuse and set the environment variable GOOGLE_APPLICATION_CREDENTIALS, which for aforementioned reasons doesn't work. AFAICT GCSFuse used to do the mounting in the main process and required separate demonisation. This is how it worked on e.g. version 0.11.0 which obeys the variable. The recent versions do the mounting in the background by demonising the process but by doing so they strip out the variable in question so the advertised way of passing credentials doesn't work.

**Comment by jacobsa** [comment] 2016-07-11 03:09
Your diagnosis makes sense to me, thanks. Will attempt to reproduce with an integration test and then fix.

**Comment by jacobsa** [comment] 2016-07-13 04:16
This should be fixed in gcsfuse 0.18.3, which has just been released.

**Closed by jacobsa** 2016-07-13 04:16 UTC
