### ISSUE TITLE
Cache-Control metadata cleared on save

### ISSUE THREAD

**Issue by gkresic** [GoogleCloudPlatform/gcsfuse#648] opened 2022-04-06 08:15 UTC
I have a file in bucket that has `Cache-Control` set to `no-store` in metadata.

If I mount this bucket using `gcsfuse` (version 0.40.0), modify a file and save it, file's `Cache-Control` metadata is cleared/unset.

**Comment by vadlakondaswetha** [comment] 2022-04-20 11:21
Can you tell how are you modifying the file. Is it via editors like vi/vim or programatically?

**Comment by gkresic** [comment] 2022-04-20 11:27
Using IntelliJ.

**Comment by vadlakondaswetha** [comment] 2022-04-22 10:33
The issue is fixed at head. The object properties will be retained if the edit is done programmatically.  Incase the edit is done via editors like vi/vim, the properties will not be retained since vi/vim deletes the original file and creates a new file. GcsFuse has no control over this behaviour. 

@gkresic, For intellij, the original file is not deleted, hence the object properties will get retained. We will soon do a release. [Meanwhile, you can try installing gcsfuse from source.](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f11f6f20c897cca5b45f3c4428bc70fb39c8d379/docs/installing.md#building-from-source)

**Comment by avidullu** [comment] 2022-04-28 10:49
Please retry with the latest release (0.41) of gcsfuse which has a fix for the same.

**Comment by gkresic** [comment] 2022-04-28 11:09
I can confirm that version 0.41.0 works OK, at least when file is edited via IntelliJ.

**Comment by avidullu** [comment] 2022-04-28 11:33
Thanks for the confirmation. Will close this issue out. Please feel free to reopen incase you find any inconsistencies.
Thanks for the help in resolving this!

**Closed by avidullu** 2022-04-28 11:33 UTC
Labels: feature request
