### ISSUE TITLE
key file ignored if not provided using env variable

### ISSUE THREAD

**Issue by erpic** [GoogleCloudPlatform/gcsfuse#474] opened 2020-12-17 12:32 UTC
Hi,

On a blank new Debian 10 system, where gcsfuse was installed using apt, starting with version 0.32.0 it appears that gcsfuse is ignoring the key file unless it is provided using the environment variable.

For example:

GOOGLE_APPLICATION_CREDENTIALS=/path/myservice-account.key.json gcsfuse --foreground --debug_http --debug_fuse --debug_gcs mybucket /mnt/mybucket

=> works, bucket mounted

gcsfuse --foreground --debug_http --debug_fuse --debug_gcs --key-file="/path//myservice-account.key.json" scilan-mybucket /mnt/mybucket

=> fails complaining that no default credentials

After downgrading to 0.30.0 (or 0.28.1) that exact same line works properly.

The same issue occurs when using /etc/fstab

**Comment by andrew-grasso** [comment] 2020-12-18 16:14
This is possibly a duplicate of #471 which has been closed as fixed by #472.

**Comment by lezh** [comment] 2021-01-21 03:56
Please upgrade to 0.33.0 that includes #472.

**Closed by lezh** 2021-01-21 03:56 UTC
