### ISSUE TITLE
GCSFuse Read/Write Perf - gcloud storage api

### ISSUE THREAD

**Issue by pmorse-cr** [GoogleCloudPlatform/gcsfuse#1300] opened 2023-08-23 14:23 UTC
**Describe the issue**
We are building a new video transcoding pipeline within Google Cloud and are looking to minimize the amount of files moving around.  In video transcoding most of the time is taken in CPU/GPU, but we have found that GCSFuse is working well for smaller source files and as soon as we src >6GB video performance drops.  We are testing copying to local-ssd/pd and filestore, but would like to maintain our use of GCSFuse and would like to know what the plans are to move to the new `gcloud storage` api/functions vs `gsutil`.  Thank you very much~!

**Comment by pmorse-cr** [comment] 2023-08-23 14:43
I apologize, it actually looks like it isn't a different API - but the difference in tooling within the sdk.   Are there any plans to change the way the gcsfuse interacts with the API for perf improvements obtained by the new `gcloud storage` tooling?  thanks

**Comment by raj-prince** [comment] 2023-08-23 17:29
Hi @pmorse-cr,

Thank you for the showing interest in GCSFuse!

Is your workload read heavy or write heavy?

To give a little context, GCSfuse is a FUSE (Filesystem in Userspace) implementation that allows you to mount a GCS bucket as a local filesystem. This means that you can access your GCS objects as if they were regular files on your computer. GCSfuse is a good option if you need to access GCS objects with standard file system operations, such as cat, ls, cp, and mv.

As far as I know, both GCSFuse and gcloud storage use similar APIs to interact with the GCS. However, in the case of GCSFuse, requests go through the kernel (by design), which can result in a difference in the performance for some operations. Still, you can follow [this](https://cloud.google.com/storage/docs/gcsfuse-performance-and-best-practices) doc to improve the performance based on your use-case.

-Prince

**Comment by raj-prince** [comment] 2023-08-28 16:29
Hi @pmorse-cr,

In addition to the above:
- Could you please also share the numbers you got b/w `gcloud storage` and gcsfuse? This will help us in understanding the gap.
- What is the expected rate of processing data through your pipeline in order to ensure smooth execution?
- You can refer [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/benchmarks.md) page, to gain a better understanding of the performance of gcsfuse for different workloads.

Also, are you talking about [these](https://cloud.google.com/blog/products/storage-data-transfer/new-gcloud-storage-cli-for-your-data-transfers) improvements?
(a) CRC32C data integrity check.
(b) Graph based tasked management to parallellize the work with less overhead.

I'll discuss within team, if we can incorporate any of these in GCSFuse. 

We look forward to hearing from you.

Thanks,
Prince Kumar.

**Comment by marcoa6** [comment] 2023-09-27 15:01
Hi @pmorse-cr you mention serverless (Cloud Run?) but then talk about using K8S (GKE). Which will be used?
If GKE, please using the integrated [GCSfuse CSI driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver). If Serverless there is a potential future integration we are exploring I can make you aware of.

Re Perf: Please see performance [best practices](https://cloud.google.com/storage/docs/gcsfuse-performance-and-best-practices), [limitations](https://cloud.google.com/storage/docs/gcs-fuse#expandable-1), and [benchmarks](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/benchmarks.md). 

Does the performance with gcloud meet your needs? If not, GCS is not the right solution. 
If this request is to support parallel downloads within GCSfuse, it is on our backlog but dont have a date yet.

**Comment by pmorse-cr** [comment] 2023-09-27 16:56
I'd love to send you my email address and collaborate more.  Is there a private way to do that vs open on this issue?  Thanks @marcoa6 @raj-prince

**Comment by marcoa6** [comment] 2023-09-27 17:56
@pmorse-cr i was trying to figure out the same :-). The best i can think of is post it here, i will ack it, and then delete your comment. The other is since it appears you have some level of communication with GCP is to ask to be routed to the GCS PM.

**Comment by pmorse-cr** [comment] 2023-09-29 13:25
@marcoa6 @raj-prince - pmorse@google.com :)

**Comment by marcoa6** [comment] 2023-09-29 15:07
We will track this as a feature request to support parallel reads in which large objects are read in chunks in parallel to improve performance

**Comment by marcoa6** [comment] 2024-08-01 16:47
Parallel downloads, which accelerates reads of large files, by using the file cache directory as a prefetch buffer using multiple workers to download large files in parallel, was released as part of GCSfuse [GCSfuse v2.4.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v2.4.0)

**Closed by marcoa6** 2024-08-01 16:47 UTC
Labels: feature request, Eng-Backlog

**Comment by raj-prince** [comment] 2025-09-10 07:58
@pmorse-cr Just wanted to update on the new feature `Buffered Read` in [GCSFuse v3.3.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v3.3.0), which accelerates large-file sequential reads (including workloads like simple file copies) (up to 2-5x).

More details about buffered-read, enablement, and cpu/memory resource usage are [here](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v3.3.0).

This feature's performance can be further improved using it with: 
- [1MB kernel read-ahead](https://cloud.google.com/storage/docs/cloud-storage-fuse/performance#increase-read-ahead-size).
- O_DIRECT for application performing large I/O operations (>= 1MB). We have plan to support O_DIRECT via GCSFuse in future release.

Please let us know if you need any help in trying it out, and we would appreciate your feedback.
