### ISSUE TITLE
Mount is missing some directories - storage.objects.get returning 404

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/gcsfuse#141] opened 2015-12-04 03:00 UTC
I mounted a directory, but when I `ls` the mountpoint, it's missing several directory.

With --debug_http, I see the directories in "prefixes", but the HTTP requests for them (below) returned 404s.
```
/storage/v1/b/bucket-name/o/09102015_1446%2F?projection=full
/storage/v1/b/bucket-name/o/temp%2F?projection=full
/storage/v1/b/bucket-name/o/09102015_1446%2F?projection=full
```
In developers.google.com/apis-explorer, I get the same 404. Three other "directories" don't return 404s. I can't determine a pattern to the names that would cause this. Furthermore, the same directory names in a new bucket don't have this problem.

(I guess this is a GCS or GCS JSON API problem, not a gcsfuse problem, unless gcsfuse should be making a different kind of request.)

**Comment by jacobsa** [comment] 2015-12-10 00:08
Hi, sorry for the slow response; I've been on vacation.

Is it possible that these are directories for which no corresponding object exists? For example, is there an object named `temp/`? See the notes on "implicit directories" [here](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/semantics.md#files-and-directories).

Closing because I assume this is the issue; re-open if not. You'll want to either create the placeholder objects or set the `--implicit-dirs` flag (but see the caveats in the link above).

**Closed by jacobsa** 2015-12-10 00:08 UTC

**Comment by zbjornson** [comment] 2015-12-10 00:10
No worries.

The directories have objects in them, but because the API is returning 404 I assume fuse is considering them empty and thus not displaying them.

**Comment by jacobsa** [comment] 2015-12-10 00:16
The issue isn't whether the directories have objects within them, but whether an (empty) object exists for the directory itself. If you do `mkdir temp` it will create an object named `temp/` and from then on the directory named `temp` will appear to exist.

**Comment by zbjornson** [comment] 2015-12-10 00:27
Aha, sorry. Yes, that was the issue.
