### ISSUE TITLE
Uploading a file with PHP in Cloud Run results in a 0 byte file in the bucket.

### ISSUE THREAD

**Issue by TheJoelGray** [GoogleCloudPlatform/gcsfuse#1039] opened 2023-04-01 00:06 UTC
**Describe the bug**
Mounting a bucket with docker image based on php:8.2-apache, the upload of a file works when I run in my local Docker Desktop, the object size in the bucket is correct, but when I deploy to Cloud Run the upload appears to work, but the object in the bucket is 0 bytes.  I can access the file for a short time (I believe until a container restart happens?).

**To Collect more Debug logs**
Log files are attached

Using the same service account and storage bucket, I run the container locally an upload the file. The file ends up in the bucket and is 137 bytes. I run it in Cloud run, it uploads the file but the file in the bucket is 0 bytes.

**System (please complete the following information):**
 - OS: Debian bullseye
 - Platform: Cloud Run
 - Version: current?

**Additional context**
I suspect it has something to do with caching. When I upload the file if I try to access it immediately after the upload, it works (I can see my PDF) but the file in the bucket is still 0 bytes. After a few minutes (presumably after a container restart or an fsync operation) I can no longer access the file as it's 0 bytes in the container as well.

[downloaded-logs-20230331-165958.zip](https://github.com/GoogleCloudPlatform/gcsfuse/files/11127965/downloaded-logs-20230331-165958.zip)

**Comment by raj-prince** [comment] 2023-04-03 12:30
@TheJoelGray, thanks for reaching out!

I looked into the attached logs, and found the below observations:-

1. Application/you tried to create a file named - user1_GPLLicenseTerms.pdf
2. I can see a writeFile call for the above object with the content of 137190 bytes (137 KB).
3. But haven't seen any Flush/sync file call after writeFile call, which actually updates the content to the GCS bucket.

You might check the `writes` sections of semantics page (https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md). As written in the documentation, cloud-storage-fuse (gcsfuse) first writes the content in a temp directory and during close/flush/sync file call it updates the content in the bucket-object.

This is the reason, you find the object with 0 byte.

So, as a fix either you need to add the instruction to invoke kernel sync/flush call. Or you need to debug, why the flush call signal doesn't come in case of cloud-run.

You might use `strace` command to know, the system details why, flush/sync call is not being invoked.

Regards and thanks,
Prince Kumar.

**Comment by sean-physna** [comment] 2023-04-18 18:09
I edited my above message to include the version being used (`0.42.3`).

However, if I downgrade to `0.41.12`, files are successfully uploaded to the bucket.

**Comment by vadlakondaswetha** [comment] 2023-04-19 05:28
Thanks for the details. As mentioned earlier, GCSFuse uploads file contents to GCS Bucket only when flushFile or syncFile is invoked. Its not an issue with GCSFuse if application is not invoking flushFile or syncFile. We need to debug why the application is not invoking flushFile/syncFile and how we can make it invoke.

Also you mentioned that even if you are running on your local machine flushFile is not getting invoked. Can you share steps on how to reproduce this and your application code. Also can you try calling explicitly os.sync() to see if flushFile/syncFile is being called.

**Comment by sean-physna** [comment] 2023-04-19 20:23
Even with explicit `os.sync()` calls, I still only see 0-byte files.  😕

-----

Here's a reproduction example, based strongly on [the GCS docs on using `gcsfuse` with Cloud Run](https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse).  

## Running it:
1. Dump the files into a directory somewhere and navigate to it
1. Build the image: `docker build -t $IMAGE_TAG .`
2. Push the image: `docker push $IMAGE_TAG`
3. Deploy Cloud Run: `gcloud run deploy --project $GCP_PROJECT_ID "example" --image $IMAGE_TAG --set-env-vars="OUTPUT_BUCKET=$YOUR_BUCKET"
4. Get the URL of the CR service, and hit it with cURL: `curl -i -X POST https://$CR_DOMAIN/doit -H "Content-Type: application/json" --data "{ \"this\": \"is a test\"}"`
5. Check the bucket for a file named `file-that-has-bytes.txt`, which, appropriately enough, should have bytes (the string "Bob was here")

### Dockerfile
```docker
FROM python:3.10-buster

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

RUN set -e; \
    apt-get update -y && apt-get install -y \
    tini \
    lsb-release; \
    gcsFuseRepo=gcsfuse-`lsb_release -c -s`; \
    echo "deb http://packages.cloud.google.com/apt $gcsFuseRepo main" | \
    tee /etc/apt/sources.list.d/gcsfuse.list; \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key add -; \
    apt-get update; \
    apt-get install -y gcsfuse \
    && apt-get clean

ENV APP_HOME /app
WORKDIR $APP_HOME

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py main.py

ENV OUTPUT_MNT_DIR /mnt/gcs-output
COPY gcsfuse_run.sh ./
# Ensure the script is executable
RUN chmod +x /app/gcsfuse_run.sh

# Use tini to manage zombie processes and signal forwarding
# https://github.com/krallin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

# Pass the startup script as arguments to Tini
CMD ["/app/gcsfuse_run.sh"]
```

### gcsfuse_run.sh
```bash
#!/usr/bin/env bash
set -eo pipefail

# Create mount directory for service
mkdir -p $OUTPUT_MNT_DIR

chmod 0777 $OUTPUT_MNT_DIR

echo "Mounting Output GCS Fuse for ${OUTPUT_BUCKET} at ${OUTPUT_MNT_DIR}."
gcsfuse --implicit-dirs --enable-storage-client-library=false --foreground --debug_fs --debug_gcs --debug_fuse --app-name "output" $OUTPUT_BUCKET $OUTPUT_MNT_DIR &
echo "Mounting completed."

# Timeout is set to 0 to disable the timeouts of the workers to allow Cloud Run to handle instance scaling.
exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app &

# # Exit immediately when one of the background processes terminate.
wait -n
```

### requirements.txt
```
Flask==2.0.2
gunicorn==20.1.0
```

### main.py
```python
import os
from flask import Flask

app = Flask(__name__)


@app.route('/doit', methods=['POST'])
def doit():
    fh = open(f'{os.environ.get("OUTPUT_MNT_DIR")}/file-that-has-bytes.txt', 'w')
    fh.writelines('Bob was here')
    fh.close()

    os.sync()

    result = f'{{ "result": "success" }}'
    print(result)
    return (result, 200)
```

**Comment by sean-physna** [comment] 2023-04-19 21:30
I found the issue, at least for me.

I can't speak to @TheJoelGray's original one for sure, but there was a bug in our deployment procedures such that we were _not_ using a `gen2` Cloud Run execution environment.  This let us read from buckets, but not fully write to them.

So - in the repro example I have, the `gcloud run deploy` should have referenced `--execution-environment gen2`.  Then it would have worked.  🤦 

Thank you for the attention, much obliged.

**Comment by sean-physna** [comment] 2023-04-19 21:31
Is there any sort of logging or error message I would have observed to indicate that the mount was insufficient?  I wonder if I could have seen my mistake sooner.

**Comment by vadlakondaswetha** [comment] 2023-04-20 10:21
This execution-environment is specific to cloud run and its not possible for gcsfuse to validate client (cloud run) specific flags.

**Comment by sethiay** [comment] 2023-05-31 06:36
Closing this issue in favor of https://github.com/GoogleCloudPlatform/gcsfuse/issues/1039#issuecomment-1516083703. Please re-open if you face any other issues.

**Closed by sethiay** 2023-05-31 06:36 UTC
Labels: pending customer action
