### ISSUE TITLE
File is there when listing files but is cannot actually read from it

### ISSUE THREAD

**Issue by aalexgabi** [GoogleCloudPlatform/gcsfuse#362] opened 2019-11-19 11:03 UTC
On one machine:
```
cd bucket-mount-folder
time dd if=/dev/zero of=10G bs=1M count=1024 oflag=dsync status=progress
```
On another machine while the first command is working
```
cd bucket-mount-folder
ls -lah
wc -c 10G
```

Output on second machine after the wc command:
```
wc: 10G: Input/output error
53474044 10G
```
The dsync flag for the dd command will fsync for every megabyte written.

Do you have any idea why this is happening?

**Comment by avidullu** [comment] 2022-04-14 09:33
Duplicate of #295

**Comment by avidullu** [comment] 2022-04-14 09:33
Closing this since as mentioned in the above issue dsync is not supported in gcsfuse

**Closed by avidullu** 2022-04-14 09:33 UTC
Labels: duplicate

**Comment by aalexgabi** [comment] 2022-04-18 20:50
@avidullu I don't understand why the second command would fail. dsync support is irrelevant when second machine is connected to the bucket because the dsync part happens between first machine and the bucket.
