### ISSUE TITLE
Issue at https://packages.cloud.google.com/apt/doc/apt-key.gpg - Non Resolving URL

### ISSUE THREAD

**Issue by christian-screen** [GoogleCloudPlatform/gcsfuse#961] opened 2023-02-26 19:22 UTC
**Describe the bug**
Attempting the Standard debian/ubuntu gpg reference per installation documentation, the URI is not available (is there an alternative URL or a mirror), https://packages.cloud.google.com/apt/doc/apt-key.gpg, the page and CuRl attempt provides the following:

`<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 500 (Internal Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>500.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>`

**To Collect more Debug logs**
1. As of 2023/02/26 2pm ET, attempt to access URL [https://packages.cloud.google.com/apt/doc/apt-key.gpg](https://packages.cloud.google.com/apt/doc/apt-key.gpg)

**System (please complete the following information):**
 - OS: Ubuntu 20.04 or Mac OS (standard CURL retrieve from terminal)

**Additional context**
N/A

**Comment by christian-screen** [comment] 2023-02-27 04:04
We created a workaround to this we thought we'd share.  Based on taking the latest version release one can simply forego the Google recommended installation using the gpg key and simply install the release as debian package.  Since our requirement was for a docker image, our RUN command appears as follows...

```
RUN set -e; \
    apt-get update -y && apt-get install -y \
    fuse \
    lsb-release; \
    curl -L -O https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.41.12/gcsfuse_0.41.12_amd64.deb; \
    dpkg --install gcsfuse_0.41.12_amd64.deb; \
    apt-get update; \
    apt-get clean;
```

This correctly installed what we needed without dealing with the dependency on the down URL.  

If anyone believes removing the dependency on the gpg and recommended reference to the down URL will have any negative affects now or down the road please share.

**Comment by Tulsishah** [comment] 2023-02-27 04:56
Hii @christian-screen, Thanks for reaching out to us. That was standard procedure to install gcsfuse via an apt-key update, but you can install it with this procedure, also. There will be no negative effects on that.

**Comment by tennysontbardwell** [comment] 2023-02-27 05:04
Workaround:

```
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
```
and similar commands can be replaced with
```
RUN echo xsBNBGKItdQBCADWmKTNZEYWgXy73FvKFY5fRro4tGNa4Be4TZW3wZpct9Cj8EjykU7S9EPoJ3EdKpxFltHRu7QbDi6LWSNA4XxwnudQrYGxnxx6Ru1KBHFxHhLfWsvFcGMwit/znpxtIt9UzqCm2YTEW5NUnzQ4rXYqVQK2FLG4weYJ5bKwkY+ZsnRJpzxdHGJ0pBiqwkMT8bfQdJymUBown+SeuQ2HEqfjVMsIRe0dweD2PHWeWo9fTXsz1Q5abiGckyOVyoN9//DgSvLUocUcZsrWvYPaN+o8lXTO3GYFGNVsx069rxarkeCjOpiQOWrQmywXISQudcusSgmmgfsRZYW7FDBy5MQrABEBAAHNUVJhcHR1cmUgQXV0b21hdGljIFNpZ25pbmcgS2V5IChjbG91ZC1yYXB0dXJlLXNpZ25pbmcta2V5LTIwMjItMDMtMDctMDhfMDFfMDEucHViKcLAYgQTAQgAFgUCYoi11AkQtT3IDRPt7wUCGwMCGQEAAMGoCAB8QBNIIN3Q2D3aahrfkb6axd55zOwR0tnriuJRoPHoNuorOpCv9aWMMvQACNWkxsvJxEF8OUbzhSYjAR534RDigjTetjK2i2wKLz/kJjZbuF4ZXMynCm40eVm1XZqU63U9XR2RxmXppyNpMqQO9LrzGEnNJuh23icaZY6no12axymxcle/+SCmda8oDAfa0iyA2iyg/eU05buZv54MC6RB13QtS+8vOrKDGr7RYp/VYvQzYWm+ck6DvlaVX6VB51BkLl23SQknyZIJBVPm8ttU65EyrrgG1jLLHFXDUqJ/RpNKq+PCzWiyt4uy3AfXK89RczLu3uxiD0CQI0T31u/IzsBNBGKItdQBCADIMMJdRcg0Phv7+CrZz3xRE8Fbz8AN+YCLigQeH0B9lijxkjAFr+thB0IrOu7ruwNY+mvdP6dAewUur+pJaIjEe+4s8JBEFb4BxJfBBPuEbGSxbi4OPEJuwT53TMJMEs7+gIxCCmwioTggTBp6JzDsT/cdBeyWCusCQwDWpqoYCoUWJLrUQ6dOlI7s6p+iIUNIamtyBCwb4izs27HdEpX8gvO9rEdtcb7399HyO3oD4gHgcuFiuZTpvWHdn9WYwPGM6npJNG7crtLnctTR0cP9KutSPNzpySeAniHx8L9ebdD9tNPCWC+OtOcGRrcBeEznkYh1C4kzdP1ORm5upnknABEBAAHCwF8EGAEIABMFAmKItdQJELU9yA0T7e8FAhsMAABJmAgAhRPk/dFj71bU/UTXrkEkZZzE9JzUgan/ttyRrV6QbFZABByf4pYjBj+yLKw3280//JWurKox2uzEq1hdXPedRHICRuh1Fjd00otaQ+wGF3kY74zlWivB6Wp6tnL9STQ1oVYBUv7HhSHoJ5shELyedxxHxurUgFAD+pbFXIiK8cnAHfXTJMcrmPpC+YWEC/DeqIyEcNPkzRhtRSuERXcq1n+KJvMUAKMD/tezwvujzBaaSWapmdnGmtRjjL7IxUeGamVWOwLQbUr+34MwzdeJdcL8fav5LA8Uk0ulyeXdwiAK8FKQsixI+xZvz7HUs8ln4pZwGw/TpvO9cMkHogtgzQ | base64 -d | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
```
as verified by a cached [wayback machine page](https://web.archive.org/web/20230101000000*/https://packages.cloud.google.com/apt/doc/apt-key.gpg) from 5 days ago.

**Comment by consideRatio** [comment] 2023-02-27 08:51
Thank you @tennysontbardwell! I verified that the provided base64 matched the the way back machines files as well.

Here is my result of making use of the cached GPG key workaround in a github actions workflow file.

```yaml
jobs:
  test-gke-plugin-setup:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null

          # FIXME: A cached version of a gpg key is used from the way back
          #        machine, dated 2023-02-23.
          #
          #        https://web.archive.org/web/20230223152417/https://packages.cloud.google.com/apt/doc/apt-key.gpg
          #
          #        The live gpg key at https://packages.cloud.google.com/apt/doc/apt-key.gpg
          #        is inaccessible with a HTTP 500 response.
          #
          #        When the live gpg key is available agian, we can revert to doing this:
          #
          #            sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg
          #
          echo "xsBNBGKItdQBCADWmKTNZEYWgXy73FvKFY5fRro4tGNa4Be4TZW3wZpct9Cj8EjykU7S9EPoJ3EdKpxFltHRu7QbDi6LWSNA4XxwnudQrYGxnxx6Ru1KBHFxHhLfWsvFcGMwit/znpxtIt9UzqCm2YTEW5NUnzQ4rXYqVQK2FLG4weYJ5bKwkY+ZsnRJpzxdHGJ0pBiqwkMT8bfQdJymUBown+SeuQ2HEqfjVMsIRe0dweD2PHWeWo9fTXsz1Q5abiGckyOVyoN9//DgSvLUocUcZsrWvYPaN+o8lXTO3GYFGNVsx069rxarkeCjOpiQOWrQmywXISQudcusSgmmgfsRZYW7FDBy5MQrABEBAAHNUVJhcHR1cmUgQXV0b21hdGljIFNpZ25pbmcgS2V5IChjbG91ZC1yYXB0dXJlLXNpZ25pbmcta2V5LTIwMjItMDMtMDctMDhfMDFfMDEucHViKcLAYgQTAQgAFgUCYoi11AkQtT3IDRPt7wUCGwMCGQEAAMGoCAB8QBNIIN3Q2D3aahrfkb6axd55zOwR0tnriuJRoPHoNuorOpCv9aWMMvQACNWkxsvJxEF8OUbzhSYjAR534RDigjTetjK2i2wKLz/kJjZbuF4ZXMynCm40eVm1XZqU63U9XR2RxmXppyNpMqQO9LrzGEnNJuh23icaZY6no12axymxcle/+SCmda8oDAfa0iyA2iyg/eU05buZv54MC6RB13QtS+8vOrKDGr7RYp/VYvQzYWm+ck6DvlaVX6VB51BkLl23SQknyZIJBVPm8ttU65EyrrgG1jLLHFXDUqJ/RpNKq+PCzWiyt4uy3AfXK89RczLu3uxiD0CQI0T31u/IzsBNBGKItdQBCADIMMJdRcg0Phv7+CrZz3xRE8Fbz8AN+YCLigQeH0B9lijxkjAFr+thB0IrOu7ruwNY+mvdP6dAewUur+pJaIjEe+4s8JBEFb4BxJfBBPuEbGSxbi4OPEJuwT53TMJMEs7+gIxCCmwioTggTBp6JzDsT/cdBeyWCusCQwDWpqoYCoUWJLrUQ6dOlI7s6p+iIUNIamtyBCwb4izs27HdEpX8gvO9rEdtcb7399HyO3oD4gHgcuFiuZTpvWHdn9WYwPGM6npJNG7crtLnctTR0cP9KutSPNzpySeAniHx8L9ebdD9tNPCWC+OtOcGRrcBeEznkYh1C4kzdP1ORm5upnknABEBAAHCwF8EGAEIABMFAmKItdQJELU9yA0T7e8FAhsMAABJmAgAhRPk/dFj71bU/UTXrkEkZZzE9JzUgan/ttyRrV6QbFZABByf4pYjBj+yLKw3280//JWurKox2uzEq1hdXPedRHICRuh1Fjd00otaQ+wGF3kY74zlWivB6Wp6tnL9STQ1oVYBUv7HhSHoJ5shELyedxxHxurUgFAD+pbFXIiK8cnAHfXTJMcrmPpC+YWEC/DeqIyEcNPkzRhtRSuERXcq1n+KJvMUAKMD/tezwvujzBaaSWapmdnGmtRjjL7IxUeGamVWOwLQbUr+34MwzdeJdcL8fav5LA8Uk0ulyeXdwiAK8FKQsixI+xZvz7HUs8ln4pZwGw/TpvO9cMkHogtgzQ==" | base64 -d | sudo tee -a /usr/share/keyrings/cloud.google.gpg

          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
```

**Comment by rohitashvadialpad** [comment] 2023-02-27 09:43
Can someone share ansible workaround also? My current ansible task is below:
```
- name: Add Google Cloud SDK GPG Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/cloud.google.gpg
```
Also, Is it a temp issue or `https://packages.cloud.google.com/apt/doc/apt-key.gpg` will be down forever? 
Many thanks in advance.

**Comment by shivangbhar** [comment] 2023-02-27 09:54
> Can someone share ansible workaround also? My current ansible task is below:
> 
> ```
> - name: Add Google Cloud SDK GPG Key
>   apt_key:
>     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
>     state: present
>     keyring: /usr/share/keyrings/cloud.google.gpg
> ```
> 
> Also, Is it a temp issue or `https://packages.cloud.google.com/apt/doc/apt-key.gpg` will be down forever? Many thanks in advance.

For ansible, I made it work like:

` echo xsBNBGKItdQBCADWmKTNZEYWgXy73FvKFY5fRro4tGNa4Be4TZW3wZpct9Cj8EjykU7S9EPoJ3EdKpxFltHRu7QbDi6LWSNA4XxwnudQrYGxnxx6Ru1KBHFxHhLfWsvFcGMwit/znpxtIt9UzqCm2YTEW5NUnzQ4rXYqVQK2FLG4weYJ5bKwkY+ZsnRJpzxdHGJ0pBiqwkMT8bfQdJymUBown+SeuQ2HEqfjVMsIRe0dweD2PHWeWo9fTXsz1Q5abiGckyOVyoN9//DgSvLUocUcZsrWvYPaN+o8lXTO3GYFGNVsx069rxarkeCjOpiQOWrQmywXISQudcusSgmmgfsRZYW7FDBy5MQrABEBAAHNUVJhcHR1cmUgQXV0b21hdGljIFNpZ25pbmcgS2V5IChjbG91ZC1yYXB0dXJlLXNpZ25pbmcta2V5LTIwMjItMDMtMDctMDhfMDFfMDEucHViKcLAYgQTAQgAFgUCYoi11AkQtT3IDRPt7wUCGwMCGQEAAMGoCAB8QBNIIN3Q2D3aahrfkb6axd55zOwR0tnriuJRoPHoNuorOpCv9aWMMvQACNWkxsvJxEF8OUbzhSYjAR534RDigjTetjK2i2wKLz/kJjZbuF4ZXMynCm40eVm1XZqU63U9XR2RxmXppyNpMqQO9LrzGEnNJuh23icaZY6no12axymxcle/+SCmda8oDAfa0iyA2iyg/eU05buZv54MC6RB13QtS+8vOrKDGr7RYp/VYvQzYWm+ck6DvlaVX6VB51BkLl23SQknyZIJBVPm8ttU65EyrrgG1jLLHFXDUqJ/RpNKq+PCzWiyt4uy3AfXK89RczLu3uxiD0CQI0T31u/IzsBNBGKItdQBCADIMMJdRcg0Phv7+CrZz3xRE8Fbz8AN+YCLigQeH0B9lijxkjAFr+thB0IrOu7ruwNY+mvdP6dAewUur+pJaIjEe+4s8JBEFb4BxJfBBPuEbGSxbi4OPEJuwT53TMJMEs7+gIxCCmwioTggTBp6JzDsT/cdBeyWCusCQwDWpqoYCoUWJLrUQ6dOlI7s6p+iIUNIamtyBCwb4izs27HdEpX8gvO9rEdtcb7399HyO3oD4gHgcuFiuZTpvWHdn9WYwPGM6npJNG7crtLnctTR0cP9KutSPNzpySeAniHx8L9ebdD9tNPCWC+OtOcGRrcBeEznkYh1C4kzdP1ORm5upnknABEBAAHCwF8EGAEIABMFAmKItdQJELU9yA0T7e8FAhsMAABJmAgAhRPk/dFj71bU/UTXrkEkZZzE9JzUgan/ttyRrV6QbFZABByf4pYjBj+yLKw3280//JWurKox2uzEq1hdXPedRHICRuh1Fjd00otaQ+wGF3kY74zlWivB6Wp6tnL9STQ1oVYBUv7HhSHoJ5shELyedxxHxurUgFAD+pbFXIiK8cnAHfXTJMcrmPpC+YWEC/DeqIyEcNPkzRhtRSuERXcq1n+KJvMUAKMD/tezwvujzBaaSWapmdnGmtRjjL7IxUeGamVWOwLQbUr+34MwzdeJdcL8fav5LA8Uk0ulyeXdwiAK8FKQsixI+xZvz7HUs8ln4pZwGw/TpvO9cMkHogtgzQ== | base64 -d > apt-key.gpg`

Save this apt-key.gpg on your package repository and use that package repostory url for your task.

**Comment by Tulsishah** [comment] 2023-02-27 10:26
It is an ongoing bug regarding the apt-get key, not the gcsfuse bug. We will update this thread once it gets fixed.

**Comment by siddhurk07** [comment] 2023-02-27 10:45
still facing this issue

**Comment by maxfisher-g** [comment] 2023-02-27 11:19
@tennysontbardwell Thank you!

One note: if you run `base64 -d` on the above string manually, it reports 'invalid input' because the string is missing padding. Adding `==` to the end of the encoded string above silences the warning.

**Comment by 0xadaw** [comment] 2023-02-27 11:41
still facing this issue, any ETAs for a fix?

**Comment by l4zyf9x** [comment] 2023-02-27 12:12
Facing the same issue when installing gcloud cli

**Comment by markjrouse** [comment] 2023-02-27 12:24
> > Can someone share ansible workaround also? My current ansible task is below:
> > ```
> > - name: Add Google Cloud SDK GPG Key
> >   apt_key:
> >     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
> >     state: present
> >     keyring: /usr/share/keyrings/cloud.google.gpg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, Is it a temp issue or `https://packages.cloud.google.com/apt/doc/apt-key.gpg` will be down forever? Many thanks in advance.
> 
> For ansible, I made it work like:
> 
> ` echo xsBNBGKItdQBCADWmKTNZEYWgXy73FvKFY5fRro4tGNa4Be4TZW3wZpct9Cj8EjykU7S9EPoJ3EdKpxFltHRu7QbDi6LWSNA4XxwnudQrYGxnxx6Ru1KBHFxHhLfWsvFcGMwit/znpxtIt9UzqCm2YTEW5NUnzQ4rXYqVQK2FLG4weYJ5bKwkY+ZsnRJpzxdHGJ0pBiqwkMT8bfQdJymUBown+SeuQ2HEqfjVMsIRe0dweD2PHWeWo9fTXsz1Q5abiGckyOVyoN9//DgSvLUocUcZsrWvYPaN+o8lXTO3GYFGNVsx069rxarkeCjOpiQOWrQmywXISQudcusSgmmgfsRZYW7FDBy5MQrABEBAAHNUVJhcHR1cmUgQXV0b21hdGljIFNpZ25pbmcgS2V5IChjbG91ZC1yYXB0dXJlLXNpZ25pbmcta2V5LTIwMjItMDMtMDctMDhfMDFfMDEucHViKcLAYgQTAQgAFgUCYoi11AkQtT3IDRPt7wUCGwMCGQEAAMGoCAB8QBNIIN3Q2D3aahrfkb6axd55zOwR0tnriuJRoPHoNuorOpCv9aWMMvQACNWkxsvJxEF8OUbzhSYjAR534RDigjTetjK2i2wKLz/kJjZbuF4ZXMynCm40eVm1XZqU63U9XR2RxmXppyNpMqQO9LrzGEnNJuh23icaZY6no12axymxcle/+SCmda8oDAfa0iyA2iyg/eU05buZv54MC6RB13QtS+8vOrKDGr7RYp/VYvQzYWm+ck6DvlaVX6VB51BkLl23SQknyZIJBVPm8ttU65EyrrgG1jLLHFXDUqJ/RpNKq+PCzWiyt4uy3AfXK89RczLu3uxiD0CQI0T31u/IzsBNBGKItdQBCADIMMJdRcg0Phv7+CrZz3xRE8Fbz8AN+YCLigQeH0B9lijxkjAFr+thB0IrOu7ruwNY+mvdP6dAewUur+pJaIjEe+4s8JBEFb4BxJfBBPuEbGSxbi4OPEJuwT53TMJMEs7+gIxCCmwioTggTBp6JzDsT/cdBeyWCusCQwDWpqoYCoUWJLrUQ6dOlI7s6p+iIUNIamtyBCwb4izs27HdEpX8gvO9rEdtcb7399HyO3oD4gHgcuFiuZTpvWHdn9WYwPGM6npJNG7crtLnctTR0cP9KutSPNzpySeAniHx8L9ebdD9tNPCWC+OtOcGRrcBeEznkYh1C4kzdP1ORm5upnknABEBAAHCwF8EGAEIABMFAmKItdQJELU9yA0T7e8FAhsMAABJmAgAhRPk/dFj71bU/UTXrkEkZZzE9JzUgan/ttyRrV6QbFZABByf4pYjBj+yLKw3280//JWurKox2uzEq1hdXPedRHICRuh1Fjd00otaQ+wGF3kY74zlWivB6Wp6tnL9STQ1oVYBUv7HhSHoJ5shELyedxxHxurUgFAD+pbFXIiK8cnAHfXTJMcrmPpC+YWEC/DeqIyEcNPkzRhtRSuERXcq1n+KJvMUAKMD/tezwvujzBaaSWapmdnGmtRjjL7IxUeGamVWOwLQbUr+34MwzdeJdcL8fav5LA8Uk0ulyeXdwiAK8FKQsixI+xZvz7HUs8ln4pZwGw/TpvO9cMkHogtgzQ== | base64 -d > apt-key.gpg`
> 
> Save this apt-key.gpg on your package repository and use that package repostory url for your task.

Hi, this fails for me with anisble returning the following error: Unable to extract key from 'inline data'", "stderr": "gpg: WARNING: no command supplied

**Comment by takwa92** [comment] 2023-02-27 15:21
still having the same error

**Comment by brandborg** [comment] 2023-02-27 15:23
In Ubuntu I fixed it by using the following command to get the key from a trusted mirror:
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05`

I have tried other suggestions without any luck.

**Comment by Senhaji-Rhazi-Hamza** [comment] 2023-02-27 15:34
Have the same problem

**Comment by intUnderflow** [comment] 2023-02-27 16:07
FYI the Kubernetes project is rehosting the key at https://dl.k8s.io/apt/doc/apt-key.gpg, see https://github.com/kubernetes/k8s.io/pull/4837

**Comment by sig-flores** [comment] 2023-02-27 16:10
I'm able to build Docker images again while using the WaybackMachine URI, will probably just stick with the Kube one though. Here's the RUN command I used in my Dockerfile for anyones ref..

`RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://web.archive.org/web/20230223152417if_/https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y
`

**Comment by tuxiqae** [comment] 2023-02-27 16:47
@sig-flores It's not really future-proof, I would not stick with it tbh

**Comment by LukeDavitt** [comment] 2023-02-27 17:46
is there an estimate on when this will be fixed?  would rather not have to impliment these work arounds

**Comment by lxfontes** [comment] 2023-02-27 18:16
working here now

**Comment by LukeDavitt** [comment] 2023-02-27 18:28
yup working for me too now

**Comment by venkatamutyala** [comment] 2023-02-27 19:26
Any plans to publish the postmortem?

**Comment by eyalzek** [comment] 2023-02-28 07:42
Issue is resolved:

> After reviewing the information you provided, we believe that you may have been affected by an issue that has already been resolved. Please review the details below to confirm that we've correctly identified your issue - GCE customers may experience issues accessing apt repositories for the first time if the GCE provided Public Images are not used:

Affected Product(s):
Compute Engine

Status:
Fully Resolved

Description:
GCE customers may experience issues accessing apt repositories for the first time if the GCE provided Public Images are not used

How to diagnose:
Affected customers would experience http 500 errors when obtaining the public signing keys from packages.cloud.google.com/apt/doc/apt-key.gpg.  New instances that do not come with the apt key ring cannot download packages from packages.cloud.google.com without a manual override.

Workaround:
Pass the flag -o Acquire::AllowInsecureRepositories=true along with the apt command, or set [trusted = yes] in the /etc/apt/sources.list config file.  Or instead, use the key ring from packages.cloud.google.com/apt/doc/yum-key.gpg.

Current update: 
At 2023-02-27 21:09 UTC (1 hour ago):
The issue with Google Compute Engine has been resolved for all affected projects as of Monday, 2023-02-27 10:14 US/Pacific.

We thank you for your patience while we worked on resolving the issue.

Previous updates:
At 2023-02-27 21:08 UTC (1 hour ago):
We are experiencing an issue with Google Compute Engine beginning at Sunday, 2023-02-27 17:46 US/Pacific.

Our engineering team continues to investigate the issue

**Comment by gabrieloliveers** [comment] 2023-02-28 23:09
> 
I am going through the same problem with this installation step of Kubectl on my CI/CD. It seems that curl is outdated. I temporarily resolved it by just ignoring this step because my runner already has Kubectl installed and there's no risk of losing this installation since the container won't be restarted. If you need to, configure it if you're using your own runner. .I hope it's helpful

**Comment by arekkusu** [comment] 2023-03-01 07:05
As per https://issuetracker.google.com/issues/270841451#comment3 the cause for HTTP/500 when retrieving this specific URL / GPG key on Google Cloud should be resolved.

**Comment by Tulsishah** [comment] 2023-03-01 07:18
Yes, It is working. apt-key is available now.

**Comment by coreyfournier** [comment] 2023-03-01 14:02
If you are using a notebook in colab this is my work around. The issue was fixed and is not occurring again.


%%shell
export GCS_FUSE_VERSION=0.41.12

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
curl -LJO "https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v${GCS_FUSE_VERSION}/gcsfuse_${GCS_FUSE_VERSION}_amd64.deb"
echo "https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v${GCS_FUSE_VERSION}/gcsfuse_${GCS_FUSE_VERSION}_amd64.deb"
apt-get -y install fuse
dpkg -i "gcsfuse_${GCS_FUSE_VERSION}_amd64.deb"

**Comment by Tulsishah** [comment] 2023-03-06 04:29
It looks issue has been resolved, but feel free to open it again if anything comes up.

**Closed by Tulsishah** 2023-03-06 04:29 UTC
Labels: bug

**Comment by mar-pan** [comment] 2023-05-18 16:26
Heyo it's not working for me today but it's working with https://dl.k8s.io/apt/doc/apt-key.gpg

**Comment by vadlakondaswetha** [comment] 2023-05-19 08:23
Its working now. Can you check again.

**Comment by HofmT** [comment] 2023-05-24 03:27
> Heyo it's not working for me today but it's working with https://dl.k8s.io/apt/doc/apt-key.gpg

I have the same issue today and using the key suggested by @mar-pan fixed it for me.

**Comment by UPiotr** [comment] 2023-05-24 18:29
> Heyo it's not working for me today but it's working with https://dl.k8s.io/apt/doc/apt-key.gpg

Worked like a charm. Thank you!
