### ISSUE TITLE
rsync'ing through gcsfuse craps out, but cp works.

### ISSUE THREAD

**Issue by webbgroup** [GoogleCloudPlatform/gcsfuse#145] opened 2015-12-24 17:29 UTC
[a21341@krusty mnt]$ rsync -auv --progress /tmp/mysqldump.sql /mnt/nl-pb-sitedev/
sending incremental file list
mysqldump.sql
   834397117 100%    1.75MB/s    0:07:35 (xfer#1, to-check=0/1)

It looks like during this rsync process fuse just stalls and doesn't close out the file.

I have the mounts like this:
nl-pb-sitedev /mnt/nl-pb-sitedev 	gcsfuse rw,noauto,user 0 0

and mounted as directed through the documentation as my user.

**Comment by webbgroup** [comment] 2015-12-24 17:38
nevermind. Copy doesn't work either...
0 -rw-r--r-- 1 a21341 a21341 0 Dec 24 10:09 devdump.sql
0 -rw-r--r-- 1 a21341 a21341 0 Dec 24 12:18 mysqldump.sql
0 -rw-r--r-- 1 a21341 a21341 0 Dec 24 11:30 .mysqldump.sql.7INdt3

**Comment by webbgroup** [comment] 2015-12-24 17:43
Using RHEL 5 with fuse-2.7.4-8.el5 and gcsfuse-0.13.0-1.x86_64.rpm

**Comment by jacobsa** [comment] 2016-01-04 00:57
Hi, sorry for the slow response over the holidays. Could you please give some more information on how to reproduce this?

Note that gcsfuse doesn't send the object to GCS until the file is closed, so it makes sense that `rsync` and `cp` would "stall" while writing 800 MB over the network at what appears to be the end of the copy.

**Comment by jacobsa** [comment] 2016-01-04 22:46
Closing because I think this is just the expected slow `close(2)` sending 800 MB of data. Please feel free to re-open if it seems I'm wrong.

**Closed by jacobsa** 2016-01-04 22:46 UTC

**Comment by webbgroup** [comment] 2016-01-23 16:51
Yeah. You might be right on this. We had to abort using gcsfuse altogether as it wasn't working...
