### ISSUE TITLE
unbearable slowness of directory listings

### ISSUE THREAD

**Issue by romange** [GoogleCloudPlatform/gcsfuse#234] opened 2017-06-22 06:58 UTC
500 files in a directory. the instance is in us-east and the storage is there as well (regional). 
```
> time gsutil ls gs:\\mybucketdir | wc -l

500
real	0m0.974s
user	0m0.484s
sys	0m0.156s

```

When running `ls /mnt/mymountpoint`

I get the following timings
```
gcs: Req             0x98: -> ListObjects() (199.70033ms): OK
gcs: Req             0x9a: <- ListObjects()
gcs: Req             0x9a: -> ListObjects() (203.140236ms): OK
gcs: Req             0x9b: <- ListObjects()
gcs: Req             0x9b: -> ListObjects() (197.373822ms): OK
gcs: Req             0x9c: <- ListObjects()
gcs: Req             0x9c: -> ListObjects() (184.619554ms): OK
gcs: Req             0x9d: <- ListObjects()
gcs: Req             0x9d: -> ListObjects() (764.47926ms): OK
gcs: Req             0x9e: <- ListObjects()
gcs: Req             0x9e: -> ListObjects() (150.530204ms): OK
gcs: Req             0x9f: <- ListObjects()
gcs: Req             0x9f: -> ListObjects() (199.542155ms): OK
gcs: Req             0xa0: <- ListObjects()
gcs: Req             0xa0: -> ListObjects() (181.239533ms): OK
gcs: Req             0xa1: <- ListObjects()
gcs: Req             0xa1: -> ListObjects() (215.307041ms): OK
gcs: Req             0xa2: <- ListObjects()
gcs: Req             0xa2: -> ListObjects() (205.366617ms): OK
gcs: Req             0xa3: <- ListObjects()
gcs: Req             0xa3: -> ListObjects() (197.569194ms): OK
gcs: Req             0xa4: <- ListObjects()
gcs: Req             0xa4: -> ListObjects() (197.323209ms): OK
gcs: Req             0xa5: <- ListObjects()
gcs: Req             0xa5: -> ListObjects() (200.654838ms): OK
gcs: Req             0xa6: <- ListObjects()
gcs: Req             0xa6: -> ListObjects() (163.866557ms): OK
gcs: Req             0xa7: <- ListObjects()
gcs: Req             0xa7: -> ListObjects() (217.490382ms): OK
gcs: Req             0xa8: <- ListObjects()
gcs: Req             0xa8: -> ListObjects() (225.55158ms): OK
gcs: Req             0xa9: <- ListObjects()
gcs: Req             0xa9: -> ListObjects() (188.412506ms): OK
gcs: Req             0xaa: <- ListObjects()
gcs: Req             0xaa: -> ListObjects() (201.611923ms): OK
gcs: Req             0xab: <- ListObjects()
gcs: Req             0xab: -> ListObjects() (203.075812ms): OK
```

it's mounted with these options: `--foreground --limit-ops-per-sec -1 --implicit-dirs -o ro -o allow_other --uid 1001 --gid 1002 --debug_gcs `
Is there any way to make it faster?  it takes few minutes to run ls compared to gsutil that takes few seconds.

**Comment by jacobsa** [comment] 2017-06-22 10:09
How many files are transitively contained in the directory? If you for example have 500 sub-directories, each of which contains 1,000 files, I believe GCS is likely to only return one single sub-directory per ListObjects request.

I'm surprised however that `gsutil` is faster, given that. Are you able to give me instructions that work for reproducing, starting with an empty bucket?

**Comment by romange** [comment] 2017-06-22 10:25
@jacobsa  There are no subdirectories in this directory, only 500 files.

**Comment by jacobsa** [comment] 2017-06-22 10:36
Is it possible that you recently deleted a bunch of other objects? Does this reproduce with a brand new bucket that you create 500 objects in?

**Comment by romange** [comment] 2017-06-22 11:45
this bucket has dozens of thousands of file but the particular "directory" (prefix) in this bucket has 500 files exactly.

**Comment by jacobsa** [comment] 2017-06-22 12:10
Good to know, but you didn't answer either of my questions.

1. Have you recently deleted a bunch of objects whose name contain the path to the directory as a prefix?

2. Can you reproduce from a fresh bucket?

**Comment by jacobsa** [comment] 2017-06-22 12:12
Also, can you confirm whether you see this issue if you don't use `--implicit-dirs`? You may need to `mkdir -p path/to/dir` before you can list it.

**Comment by romange** [comment] 2017-06-22 12:20
1. I did not delete objects from this bucket. They are only added to it on daily basis.
2. What does it mean "fresh bucket"?  Do you want me create new bucket & copy there 500 files and run ls on its fuse mount or another existing bucket that is freshly mount is also ok ?
3. We mount in read-only mode so mkdir won't work for us.

**Comment by jacobsa** [comment] 2017-06-22 12:24
Thanks. By fresh bucket I mean a brand new bucket. You could `touch` 500 files for example. Please try without `--implicit-dirs` as well.

I suspect maybe what's happened is that the default number of objects returned by GCS per `ListObjects` request has changed. Is your log above complete, or truncated? If complete, it shows that it must be returning 25 objects per request. 

If that's the problem, [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/7149e604520f3db3748761e0b4fbf9eb27aa215b/internal/fs/inode/dir.go#L678-L682) code would need to be modified to set `MaxResults` to 1,000 (the maximum supported by GCS, and what gsutil [uses](https://github.com/GoogleCloudPlatform/gsutil/blob/2120f850fe2eb492a4d788641a88cccbd4558353/gslib/util.py#L126-L127)).

**Comment by romange** [comment] 2017-06-22 12:32
If we mount in writerable mode without `--implicit-dirs` it works much faster after 2 seconds I got the listing.
The log is truncated.
When mounting a fresh bucket it worked much faster even with  `--implicit-dirs`  option

**Comment by jacobsa** [comment] 2017-06-23 02:44
Could you please try minimal differences from your usual config? That is, mount read-only without `--implicit-dirs`, and read/write with `--implicit-dirs`.

**Comment by romange** [comment] 2017-06-23 06:19
I do not understand how to work with read-only mount without "--implicit-dirs" - it does not should me the directories and it gives me " No such file or directory" when I tried to ls them. This is why we used this option in the first place.

Surprisingly, now any option with gcsfuse works fast and the request listing is much shorter! I do not understand what happens. Full listing below with options:
`gcsfuse --foreground  -o allow_other -o ro --implicit-dirs   --uid 1001 --gid 1002 --limit-ops-per-sec -1 --debug_gcs ubieast /ubimo/east2`

```
time ls  /ubimo/east2/mydataset/ym=2017-06/dd=03/ | wc -l
gcs: Req              0x1: <- StatObject("harbor_counts")
gcs: Req              0x3: <- StatObject("harbor_counts/")
gcs: Req              0x2: <- ListObjects()
gcs: Req              0x1: -> StatObject("harbor_counts") (40.065192ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x3: -> StatObject("harbor_counts/") (43.995664ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x2: -> ListObjects() (232.255188ms): OK
gcs: Req              0x4: <- ListObjects()
gcs: Req              0x5: <- StatObject("harbor_counts/ym=2017-06")
gcs: Req              0x6: <- StatObject("harbor_counts/ym=2017-06/")
gcs: Req              0x6: -> StatObject("harbor_counts/ym=2017-06/") (35.133425ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x5: -> StatObject("harbor_counts/ym=2017-06") (39.872907ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x4: -> ListObjects() (190.290325ms): OK
gcs: Req              0x7: <- StatObject("harbor_counts/ym=2017-06/dd=03")
gcs: Req              0x8: <- ListObjects()
gcs: Req              0x9: <- StatObject("harbor_counts/ym=2017-06/dd=03/")
gcs: Req              0x9: -> StatObject("harbor_counts/ym=2017-06/dd=03/") (31.486524ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x7: -> StatObject("harbor_counts/ym=2017-06/dd=03") (45.052541ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x8: -> ListObjects() (185.64592ms): OK
gcs: Req              0xa: <- ListObjects()
gcs: Req              0xa: -> ListObjects() (203.076368ms): OK
gcs: Req              0xb: <- ListObjects()
gcs: Req              0xb: -> ListObjects() (187.4465ms): OK
gcs: Req              0xc: <- ListObjects()
gcs: Req              0xc: -> ListObjects() (227.215982ms): OK
gcs: Req              0xd: <- ListObjects()
gcs: Req              0xd: -> ListObjects() (661.99406ms): OK
500

time ls  /ubimo/east2/harbor_counts/ym=2017-06/dd=03/ | wc -l
gcs: Req              0x1: <- StatObject("harbor_counts")
gcs: Req              0x3: <- StatObject("harbor_counts/")
gcs: Req              0x2: <- ListObjects()
gcs: Req              0x1: -> StatObject("harbor_counts") (40.065192ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x3: -> StatObject("harbor_counts/") (43.995664ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x2: -> ListObjects() (232.255188ms): OK
gcs: Req              0x4: <- ListObjects()
gcs: Req              0x5: <- StatObject("harbor_counts/ym=2017-06")
gcs: Req              0x6: <- StatObject("harbor_counts/ym=2017-06/")
gcs: Req              0x6: -> StatObject("harbor_counts/ym=2017-06/") (35.133425ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x5: -> StatObject("harbor_counts/ym=2017-06") (39.872907ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x4: -> ListObjects() (190.290325ms): OK
gcs: Req              0x7: <- StatObject("harbor_counts/ym=2017-06/dd=03")
gcs: Req              0x8: <- ListObjects()
gcs: Req              0x9: <- StatObject("harbor_counts/ym=2017-06/dd=03/")
gcs: Req              0x9: -> StatObject("harbor_counts/ym=2017-06/dd=03/") (31.486524ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x7: -> StatObject("harbor_counts/ym=2017-06/dd=03") (45.052541ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x8: -> ListObjects() (185.64592ms): OK
gcs: Req              0xa: <- ListObjects()
gcs: Req              0xa: -> ListObjects() (203.076368ms): OK
gcs: Req              0xb: <- ListObjects()
gcs: Req              0xb: -> ListObjects() (187.4465ms): OK
gcs: Req              0xc: <- ListObjects()
gcs: Req              0xc: -> ListObjects() (227.215982ms): OK
gcs: Req              0xd: <- ListObjects()
gcs: Req              0xd: -> ListObjects() (661.99406ms): OK
500
time ls  /ubimo/east2/harbor_counts/ym=2017-06/dd=03/ | wc -l
gcs: Req              0x1: <- StatObject("harbor_counts")
gcs: Req              0x3: <- StatObject("harbor_counts/")
gcs: Req              0x2: <- ListObjects()
gcs: Req              0x1: -> StatObject("harbor_counts") (40.065192ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x3: -> StatObject("harbor_counts/") (43.995664ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x2: -> ListObjects() (232.255188ms): OK
gcs: Req              0x4: <- ListObjects()
gcs: Req              0x5: <- StatObject("harbor_counts/ym=2017-06")
gcs: Req              0x6: <- StatObject("harbor_counts/ym=2017-06/")
gcs: Req              0x6: -> StatObject("harbor_counts/ym=2017-06/") (35.133425ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x5: -> StatObject("harbor_counts/ym=2017-06") (39.872907ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x4: -> ListObjects() (190.290325ms): OK
gcs: Req              0x7: <- StatObject("harbor_counts/ym=2017-06/dd=03")
gcs: Req              0x8: <- ListObjects()
gcs: Req              0x9: <- StatObject("harbor_counts/ym=2017-06/dd=03/")
gcs: Req              0x9: -> StatObject("harbor_counts/ym=2017-06/dd=03/") (31.486524ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x7: -> StatObject("harbor_counts/ym=2017-06/dd=03") (45.052541ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x8: -> ListObjects() (185.64592ms): OK
gcs: Req              0xa: <- ListObjects()
gcs: Req              0xa: -> ListObjects() (203.076368ms): OK
gcs: Req              0xb: <- ListObjects()
gcs: Req              0xb: -> ListObjects() (187.4465ms): OK
gcs: Req              0xc: <- ListObjects()
gcs: Req              0xc: -> ListObjects() (227.215982ms): OK
gcs: Req              0xd: <- ListObjects()
gcs: Req              0xd: -> ListObjects() (661.99406ms): OK
500

real	0m1.897s
user	0m0.000s
sys	0m0.000s

```

**Comment by jacobsa** [comment] 2017-06-25 23:15
You can do a read-only mount without `--implicit-dirs` just like you would do any read-only mount; just leave out that flag. If your directory isn't available that way, then mount the file system read/write without `--implicit-dirs`, do `mkdir -p path/to/dir` once to add the missing object, then unmount and mount read-only.

In any case, it sounds like this was a transient GCS issue causing listings with fewer objects than normal. I've confirmed that listing 502 objects takes 1.4 seconds for me and requires only one call to `ListObjects` (you have more because you use `--implicit-dirs`). So closing this. Please re-open if you can reproduce it again.

**Comment by romange** [comment] 2017-06-26 07:42
@jacobsa  I can reproduce. Can you please repopen it?
I mounted it in non-readonly mode. It sends tons of requests. When I hit ctrl-c I got the output below:
Why maxResults=1 ?

```
......
gcs: Req             0x63: -> ListObjects() (222.774809ms): OK
gcs: Req             0x64: <- ListObjects()
gcs: Req             0x64: -> ListObjects() (191.324502ms): OK
gcs: Req             0x65: <- ListObjects()
gcs: Req             0x65: -> ListObjects() (225.454641ms): OK
gcs: Req             0x66: <- ListObjects()
gcs: Req             0x66: -> ListObjects() (150.545595ms): OK
gcs: Req             0x67: <- ListObjects()
gcs: Req             0x67: -> ListObjects() (235.490697ms): OK
gcs: Req             0x68: <- ListObjects()
gcs: Req             0x68: -> ListObjects() (202.584064ms): OK
gcs: Req             0x69: <- ListObjects()
gcs: Req             0x69: -> ListObjects() (182.854594ms): OK
gcs: Req             0x6a: <- ListObjects()
gcs: Req             0x6a: -> ListObjects() (224.241402ms): OK
gcs: Req             0x6b: <- ListObjects()
gcs: Req             0x6b: -> ListObjects() (181.813158ms): OK
gcs: Req             0x6c: <- ListObjects()
gcs: Req             0x6c: -> ListObjects() (187.754036ms): OK
gcs: Req             0x6d: <- ListObjects()
^Cgcs: Req             0x6d: -> ListObjects() (72.885926ms): Get https://www.googleapis.com/storage/v1/b/ubieast/o?maxResults=1&prefix=idcounts%2Fym%3D2017-06%2Fdd%3D01%2F&projection=full: net/http: request canceled
fuse: 2017/06/26 07:38:17.088530 *fuseops.LookUpInodeOp error: LookUpChild: objectNamePrefixNonEmpty: ListObjects: Get https://www.googleapis.com/storage/v1/b/ubieast/o?maxResults=1&prefix=idcounts%2Fym%3D2017-06%2Fdd%3D01%2F&projection=full: net/http: request canceled
gcs: Req             0x6e: <- ListObjects()
gcs: Req             0x6e: -> ListObjects() (169.552µs): Get https://www.googleapis.com/storage/v1/b/ubieast/o?maxResults=1&prefix=idcounts%2Fym%3D2017-06%2Fdd%3D01%2F&projection=full: net/http: request canceled
fuse: 2017/06/26 07:38:17.089316 *fuseops.LookUpInodeOp error: LookUpChild: objectNamePrefixNonEmpty: ListObjects: Get https://www.googleapis.com/storage/v1/b/ubieast/o?maxResults=1&prefix=idcounts%2Fym%3D2017-06%2Fdd%3D01%2F&projection=full: net/http: request canceled
ls: cannot access ...': Input/output error
```

**Comment by romange** [comment] 2017-06-26 08:15
In implicit dir mode during listing of `prefix/` for each file `prefix/foo` you check if it's not a potential directory `prefix/foo/` by issuing a special request, am i correct ? Won't you get both `prefix/foo` and `prefix/foo/bar` when asking for  `prefix/` in the first place?

**Comment by romange** [comment] 2017-06-26 08:23
Scratch that, it's not what happens....
I see the following requests are issued multiple times ( I did grep on maxResults=1)
```
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/dd=05/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/&projection=full HTTP/1.1
GET http://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&prefix=idcounts/ym=2017-06/&projection=full HTTP/1.1
```

**Comment by jacobsa** [comment] 2017-06-26 08:53
Could you run with `--debug_http` and see what the listing responses look like?

The requests with `MaxResults` set to 1 are due to the use of `--implicit-dirs`, and are exactly why the documentation says you should try to avoid `--implicit-dirs`. But I believe at most this should double the amount of work.

**Comment by romange** [comment] 2017-06-26 09:02
I can send you the output of debug http but I prefer not to post it here. Can I send it to email appearing in your github profile?

**Comment by jacobsa** [comment] 2017-06-26 09:10
Sure, sounds good.

**Comment by romange** [comment] 2017-06-26 19:19
I've sent it

**Comment by jacobsa** [comment] 2017-06-27 03:15
Thanks for the log, and sorry for the slow response. It's really hard to separate the `ListObjects` responses that are necessary for listing the directory from those that are necessary because of `--implicit-dirs`. Could you please collect a log without `--implicit-dirs`, and clarify whether you still see the slowness?

Again, to make this happen, you'll need to ensure that underlying `foo/bar/` objects exist for each directory `foo/bar` in the file system. If you can't see your directory `foo/bar` after mounting without `--implicit-dirs`, then run:

    mkdir foo
    mkdir foo/bar

and now you should be able to see it.

**Comment by romange** [comment] 2017-06-27 06:04
Hi Aaron, it's not slow without `implicit-dirs`. My point is that this option should make things slower but not as slow as it does today. There is no reason to have > 60s delay when listing 500 files directory !

**Comment by jacobsa** [comment] 2017-06-27 06:48
Ah okay, it's good to know that it's not slow without `--implicit-dirs`. This is making more sense now. Sorry it's taken so long.

I forgot to ask before:

1. Which OS are you using? Specific version?
2. Does this still happen if you use `ls -1` rather instead of `ls -l` or just `ls`?

I suspect what's happening here is that the listing from GCS itself completes in a reasonable amount of time, and includes all 500 objects. This causes gcsfuse to respond quickly to the `readdir` op (you can confirm this with `--debug_fuse`).

But after this, either the OS or the `ls` process decides to `stat` each result one by one, 500 times. Because you're using `--implicit-dirs`, each `stat` requires a `ListObjects` request. (This is why you shouldn't use `--implicit-dirs`.) It looks like your latency to GCS is >150 ms, and 500 times 150 ms is 75 seconds.

The one thing I remain confused about is why [the type caching code](7149e604520f3db3748761e0b4fbf9eb27aa215b) in `dirInode.ReadEntries` doesn't cause the later call to `LookUpChild` to [skip](https://github.com/GoogleCloudPlatform/gcsfuse/blob/7149e604520f3db3748761e0b4fbf9eb27aa215b/internal/fs/inode/dir.go#L636-L644) the extra implicit dir lookup.

Could you please post a full log with `--debug_fuse` and `--debug_gcs`? That should much more clearly show what's happening. The HTTP dump isn't necessary.

Could you also clarify: you're not setting `--type-cache-ttl`, are you?

Thanks for bearing with me.

**Comment by romange** [comment] 2017-06-27 07:19
1. Ubuntu 16
2. You are absolutely right. We had `alias ls='ls --color=auto'` so that probably caused additional requests :(
3. Once I used `'ls' <fusedir>`  the speed became adequate!

We are not setting `--type-cache-ttl` but from help it should have 1min cache, am I right? should we increase it ?

**Comment by jacobsa** [comment] 2017-06-27 08:13
Thanks. You shouldn't need to set `--type-cache-ttl` by my reading either, so this remains my confusion. Can you post a log with `--debug_fuse --debug_gcs --implicit-dirs`?

**Comment by jacobsa** [comment] 2017-06-27 22:02
Thanks for sending the log. With the `--debug_fuse` output I can now see what's going on. For the sake of posterity, I'm posting the leading portion of the log below, with directory and file names redacted.

This is for running `ls --color=auto /mntpoint/parent1/parent2/parent3/`, with gcsfuse mounted using `--implicit-dirs`.

    Using mount point: /ubimo/east
    Opening GCS connection...
    Opening bucket...
    gcs: Req              0x0: <- ListObjects()
    gcs: Req              0x0: -> ListObjects() (254.550252ms): OK
    Mounting file system...
    fuse_debug: Op 0x00000001        connection.go:395] <- init
    fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
    File system has been successfully mounted.
    fuse_debug: Op 0x00000002        connection.go:395] <- GetInodeAttributes (inode 1)
    fuse_debug: Op 0x00000002        connection.go:474] -> OK ()
    fuse_debug: Op 0x00000003        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req              0x1: <- ListObjects()
    gcs: Req              0x2: <- StatObject("parent1")
    gcs: Req              0x3: <- StatObject("parent1/")
    gcs: Req              0x2: -> StatObject("parent1") (49.033757ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
    gcs: Req              0x3: -> StatObject("parent1/") (72.178894ms): OK
    gcs: Req              0x1: -> ListObjects() (254.907424ms): OK
    fuse_debug: Op 0x00000003        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x00000004        connection.go:395] <- LookUpInode (parent 2, name "parent2")
    gcs: Req              0x4: <- ListObjects()
    gcs: Req              0x5: <- StatObject("parent1/parent2")
    gcs: Req              0x6: <- StatObject("parent1/parent2/")
    gcs: Req              0x5: -> StatObject("parent1/parent2") (52.982038ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
    gcs: Req              0x6: -> StatObject("parent1/parent2/") (69.350561ms): OK
    gcs: Req              0x4: -> ListObjects() (162.533908ms): OK
    fuse_debug: Op 0x00000004        connection.go:474] -> OK (inode 3)
    fuse_debug: Op 0x00000005        connection.go:395] <- LookUpInode (parent 3, name "parent3")
    gcs: Req              0x7: <- StatObject("parent1/parent2/parent3")
    gcs: Req              0x8: <- ListObjects()
    gcs: Req              0x9: <- StatObject("parent1/parent2/parent3/")
    gcs: Req              0x7: -> StatObject("parent1/parent2/parent3") (54.228636ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
    gcs: Req              0x9: -> StatObject("parent1/parent2/parent3/") (62.542072ms): OK
    gcs: Req              0x8: -> ListObjects() (239.473957ms): OK
    fuse_debug: Op 0x00000005        connection.go:474] -> OK (inode 4)
    fuse_debug: Op 0x00000006        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req              0xa: <- ListObjects()
    gcs: Req              0xa: -> ListObjects() (167.671106ms): OK
    fuse_debug: Op 0x00000006        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x00000007        connection.go:395] <- LookUpInode (parent 2, name "parent2")
    gcs: Req              0xb: <- ListObjects()
    gcs: Req              0xb: -> ListObjects() (220.816242ms): OK
    fuse_debug: Op 0x00000007        connection.go:474] -> OK (inode 3)
    fuse_debug: Op 0x00000008        connection.go:395] <- LookUpInode (parent 3, name "parent3")
    gcs: Req              0xc: <- ListObjects()
    gcs: Req              0xc: -> ListObjects() (200.543335ms): OK
    fuse_debug: Op 0x00000008        connection.go:474] -> OK (inode 4)
    fuse_debug: Op 0x00000009        connection.go:395] <- OpenDir (inode 4)
    fuse_debug: Op 0x00000009        connection.go:474] -> OK ()
    fuse_debug: Op 0x0000000a        connection.go:395] <- ReadDir (inode 4)
    gcs: Req              0xd: <- ListObjects()
    gcs: Req              0xd: -> ListObjects() (1.852518768s): OK
    fuse_debug: Op 0x0000000a        connection.go:474] -> OK ()
    fuse_debug: Op 0x0000000b        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req              0xe: <- ListObjects()
    gcs: Req              0xe: -> ListObjects() (251.362257ms): OK
    fuse_debug: Op 0x0000000b        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x0000000c        connection.go:395] <- LookUpInode (parent 2, name "parent2")
    gcs: Req              0xf: <- ListObjects()
    gcs: Req              0xf: -> ListObjects() (187.784336ms): OK
    fuse_debug: Op 0x0000000c        connection.go:474] -> OK (inode 3)
    fuse_debug: Op 0x0000000d        connection.go:395] <- LookUpInode (parent 3, name "parent3")
    gcs: Req             0x10: <- ListObjects()
    gcs: Req             0x10: -> ListObjects() (228.835581ms): OK
    fuse_debug: Op 0x0000000d        connection.go:474] -> OK (inode 4)
    fuse_debug: Op 0x0000000e        connection.go:395] <- LookUpInode (parent 4, name "file-0000")
    fuse_debug: Op 0x0000000e        connection.go:474] -> OK (inode 5)
    fuse_debug: Op 0x0000000f        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req             0x11: <- ListObjects()
    gcs: Req             0x11: -> ListObjects() (188.495048ms): OK
    fuse_debug: Op 0x0000000f        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x00000010        connection.go:395] <- LookUpInode (parent 2, name "parent2")
    gcs: Req             0x12: <- ListObjects()
    gcs: Req             0x12: -> ListObjects() (171.51587ms): OK
    fuse_debug: Op 0x00000010        connection.go:474] -> OK (inode 3)
    fuse_debug: Op 0x00000011        connection.go:395] <- LookUpInode (parent 3, name "parent3")
    gcs: Req             0x13: <- ListObjects()
    gcs: Req             0x13: -> ListObjects() (228.927968ms): OK
    fuse_debug: Op 0x00000011        connection.go:474] -> OK (inode 4)
    fuse_debug: Op 0x00000012        connection.go:395] <- LookUpInode (parent 4, name "file-0001")
    fuse_debug: Op 0x00000012        connection.go:474] -> OK (inode 6)
    fuse_debug: Op 0x00000013        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req             0x14: <- ListObjects()
    gcs: Req             0x14: -> ListObjects() (161.306221ms): OK
    fuse_debug: Op 0x00000013        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x00000014        connection.go:395] <- LookUpInode (parent 2, name "parent2")
    gcs: Req             0x15: <- ListObjects()
    gcs: Req             0x15: -> ListObjects() (305.978979ms): OK
    fuse_debug: Op 0x00000014        connection.go:474] -> OK (inode 3)
    fuse_debug: Op 0x00000015        connection.go:395] <- LookUpInode (parent 3, name "parent3")
    gcs: Req             0x16: <- ListObjects()
    gcs: Req             0x16: -> ListObjects() (192.817882ms): OK
    fuse_debug: Op 0x00000015        connection.go:474] -> OK (inode 4)
    fuse_debug: Op 0x00000016        connection.go:395] <- LookUpInode (parent 4, name "file-0002")
    fuse_debug: Op 0x00000016        connection.go:474] -> OK (inode 7)
    fuse_debug: Op 0x00000017        connection.go:395] <- LookUpInode (parent 1, name "parent1")
    gcs: Req             0x17: <- ListObjects()
    gcs: Req             0x17: -> ListObjects() (200.761433ms): OK
    fuse_debug: Op 0x00000017        connection.go:474] -> OK (inode 2)
    fuse_debug: Op 0x00000018        connection.go:395] <- LookUpInode (parent 2, name "parent2")


Everything up to the `ReadDir` op looks sane. Strictly listing the directory is not particularly slow (as you confirmed before with `ls -1`).

But then `ls` goes to stat each object, and this results in a `LookUpInode` request for each of the three ancestor directories. (I don't know why this is, but it's the decision of the kernel's VFS layer and is presumably for a sane reason.)

The type cache [successfully avoids](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f1a018ccd5ceb359f4ec9c72963c45a0a4d9c1eb/internal/fs/inode/dir.go#L628-L634) a lookup as a file, so we look up the inodes only [as directories](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f1a018ccd5ceb359f4ec9c72963c45a0a4d9c1eb/internal/fs/inode/dir.go#L636-L644). Since you're using `--implicit-dirs`, this [involves](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f1a018ccd5ceb359f4ec9c72963c45a0a4d9c1eb/internal/fs/inode/dir.go#L290-L306) a [call](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f1a018ccd5ceb359f4ec9c72963c45a0a4d9c1eb/internal/fs/inode/dir.go#L350-L368) to `ListObjects` to confirm that the implicit directory still exists. Once all of the directories are looked up, a `LookUpInode` is received for the file, and responded to from cache (since we have a backing object record in our cache from the earlier calls to `ListObjects`).

Therefore the 500 stat calls from `ls` turn into 1500 calls to `ListObjects`. This is in contrast to `gsutil ls`, which I believe does nothing but a single `ListObjects` request.

Unfortunately this is the cost of pretending to be a file system with directory inodes, but not actually having GCS objects to back them. The correct fix here is to not use `--implicit-dirs`.

**Comment by jacobsa** [comment] 2017-08-09 00:07
Closing this because I think it's working as best as possible.

**Closed by jacobsa** 2017-08-09 00:07 UTC

**Comment by romange** [comment] 2017-08-12 23:38
Thanks!
