### ISSUE TITLE
Permission issue mounting a Google Cloud Storage Bucket with gcsfuse 0.42.1. No issues with 0.41.12

### ISSUE THREAD

**Issue by christidis** [GoogleCloudPlatform/gcsfuse#982] opened 2023-03-02 11:02 UTC
**Describe the bug**
I am facing an issue mounting a Google Cloud storage bucket with gcsfuse `0.42.1`. No issues with `0.41.12`.

**System (please complete the following information):**
 - OS: [Docker image from Ubuntu 22.04]
 - Platforms [Docker, GKE]
 - GKE Version [1.24.9]
 - Docker version [23.0.1]

```
# lsb_release -c -s
jammy
# apt-cache madison gcsfuse | head -5
   gcsfuse |     0.42.1 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.42.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.12 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.11 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.10 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
# gcsfuse --version
gcsfuse version 0.42.1 (Go version go1.19.5)
```

**Additional context**
I am running gcsfuse on Docker but have initially verified this in GKE 1.24.9.  
Debugging this it turns out to be an issue with the latest version `0.42.1`:
```
# gcsfuse --log-file=/opt/gcsfuse-0-42-1.log --debug_gcs --debug_fs --debug_fuse --debug_http --debug_invariants --debug_mutex --debug_fuse_errors --key-file=/opt/sa.json --app-name test deployment_models dest        
2023/03/02 10:47:50.309836 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "test" using mount point: /opt/dest
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: OpenBucket: googleapi: Error 403: id@appspot.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden

# cat gcsfuse-0-42-1.log 
{"name":"root","levelname":"INFO","severity":"INFO","message":"Start gcsfuse/0.42.1 (Go version go1.19.5) for app \"test\" using mount point: /opt/dest\n","timestampSeconds":1677754070,"timestampNanos":324377479}
{"name":"root","levelname":"NOTICE","severity":"NOTICE","message":"Opening GCS connection...\n","timestampSeconds":1677754070,"timestampNanos":324588814}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Creating a mount at \"/opt/dest\"\n","timestampSeconds":1677754070,"timestampNanos":379789245}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Creating a new server...\n","timestampSeconds":1677754070,"timestampNanos":379902768}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Set up root directory for bucket deployment_models\n","timestampSeconds":1677754070,"timestampNanos":379910109}
```

Note: I am getting a similar error with `--foreground` flag set (the log file logs the same information):
```
# gcsfuse --foreground --log-file=/opt/gcsfuse-0-42-1.log --debug_gcs --debug_fs --debug_fuse --debug_http --debug_invariants --debug_mutex --debug_fuse_errors --key-file=/opt/sa.json --app-name test deployment_models dest        

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.
mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: OpenBucket: googleapi: Error 403: id@appspot.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden
```

The same command works just fine if I downgrade the binary to `0.41.12`.
```
# apt-get -y install gcsfuse=0.41.12
...
...
# gcsfuse --log-file=/opt/gcsfuse-0-41-12.log --debug_gcs --debug_fs --debug_fuse --debug_http --debug_invariants --debug_mutex --debug_fuse_errors --key-file=/opt/sa.json --app-name test deployment_models dest
2023/03/02 10:48:22.406857 Start gcsfuse/0.41.12 (Go version go1.18.4) for app "test" using mount point: /opt/dest
#
```

**Comment by Tulsishah** [comment] 2023-03-02 15:00
Hi @christidis, can you please share your docker file?
I tried to reproduce the issue, but it worked fine for me.

**Comment by christidis** [comment] 2023-03-02 16:48
Sure. 

Dockerfile
```
FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y \
    wget  \
    gnupg \
    lsb-release && \
    echo "deb http://packages.cloud.google.com/apt gcsfuse-`lsb_release -c -s` main" > /etc/apt/sources.list.d/gcsfuse.list && \
    #Use the following if wget failed
    #apt-key adv --keyserver keyserver.ubuntu.com --recv B53DC80D13EDEF05 && \
    wget https://packages.cloud.google.com/apt/doc/apt-key.gpg && \
    apt-key add apt-key.gpg && \
    apt-get update && \
    apt-get install -y gcsfuse=0.42.1 &&\
    mkdir /opt/dest
 ```
Docker run 
```
docker run --privileged --name=issue-gcsfuse -ti --rm issue-gcsfuse:latest bash
```

I copy the sa.json manually from the docker host
```
docker cp sa.json issue-gcsfuse:/opt/sa.json
```

then I attempt to mount bucket with `0.42.1`
```
root@c1b1aa9bd0d2:/# gcsfuse --log-file=/opt/gcsfuse-0-42-1.log --debug_gcs --debug_fs --debug_fuse --debug_http --debug_invariants --debug_mutex --debug_fuse_errors --key-file=/opt/sa.json --app-name test deployment_models /opt/dest
2023/03/02 16:40:48.262138 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "test" using mount point: /opt/dest
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: OpenBucket: googleapi: Error 403: information-discovery@appspot.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden
```

debug logs don't say much (see the first comment)

then I downgrade `gcsfuse` to `0.41.12`.
```
root@c1b1aa9bd0d2:/# apt install gcsfuse=0.41.12 -y --allow-downgrades 
```

just to verify that mount works.
```
root@c1b1aa9bd0d2:/# gcsfuse --log-file=/opt/gcsfuse-0-41-12.log --debug_gcs --debug_fs --debug_fuse --debug_http --debug_invariants --debug_mutex --debug_fuse_errors --key-file=/opt/sa.json --app-name test deployment_models /opt/dest
2023/03/02 16:41:33.487802 Start gcsfuse/0.41.12 (Go version go1.18.4) for app "test" using mount point: /opt/dest
root@c1b1aa9bd0d2:/# df -h /opt/dest
Filesystem         Size  Used Avail Use% Mounted on
deployment_models  1.0P     0  1.0P   0% /opt/dest
```

The repository seems to be well configured
```
root@2508235b7e9f:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
root@2508235b7e9f:/# apt-cache madison gcsfuse
   gcsfuse |     0.42.1 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.42.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.12 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.11 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |    0.41.10 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.9 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.8 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.7 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.6 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.5 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.4 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.3 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.2 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.1 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.41.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.40.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.39.2 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.39.1 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.39.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.38.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.37.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.36.0 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
   gcsfuse |     0.35.1 | http://packages.cloud.google.com/apt gcsfuse-jammy/main amd64 Packages
root@2508235b7e9f:/# cat /etc/apt/sources.list.d/gcsfuse.list 
deb http://packages.cloud.google.com/apt gcsfuse-jammy main
```

**Comment by danking** [comment] 2023-03-02 19:59
We have observed the same issue. Invocation:
```
/usr/bin/gcsfuse     -o allow_other,ro     --file-mode 770     --dir-mode 770     --implicit-dirs     --key-file /batch/2a454df25cf64f888d16cdc5979df23e/cloudfuse/key.json     --billing-project "hail-vdc"     hail-services-requester-pays /cloudfuse/2a454df25cf64f888d16cdc5979df23e/hail-services-requester-pays/data
```
Output:
```
2023/03/02 16:36:01.512353 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /cloudfuse/2a454df25cf64f888d16cdc5979df23e/hail-services-requester-pays/data
2023/03/02 16:36:01.527811 Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: OpenBucket: googleapi: Error 403: test-665@hail-vdc.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden
```

I will confirm that downgrading fixes the issue. I strongly prefer that gcsfuse does not require `storage.buckets.get` because [the roles which grant that permission](https://cloud.google.com/storage/docs/access-control/iam-roles) also grant lots of other permissions.

**Comment by Tulsishah** [comment] 2023-03-03 04:49
For now, you can pass the-enable-storage-client-library=false flag in the latest version. Currently, We are looking into it. We will let you know once it gets fixed.

**Comment by christidis** [comment] 2023-03-03 16:30
I can verify that the suggested workaround works with `0.42.1`. Thank you @Tulsishah.

**Comment by WobblyRobbly** [comment] 2023-03-09 23:04
We add entries to the `/etc/fstab`  file using `gcsfuse_mount` however it doesn't look as though that handles being able to set the value `=false` to disable it

https://github.com/GoogleCloudPlatform/gcsfuse/blob/13d73e27d22a51ba5d71286f745ef32e2964cac8/tools/mount_gcsfuse/main.go#L90

I tried

`    mount_line = ('%s /sftp/%s/upload gcsfuse rw,'
                  '_netdev,allow_other,uid=%u,gid=%u,enable_storage_client_library=false' %
                  (fuse_bucket, account['user'], uid, gid))`

which just ignored the flag

`    mount_line = ('%s /sftp/%s/upload gcsfuse rw,'
                  '_netdev,allow_other,uid=%u,gid=%u,--enable-storage-client-library=false' %
                  (fuse_bucket, account['user'], uid, gid))`
                  
                  
and this didn't work, it add `-o --enable-storage-client-library=false` 

Am I doing something wrong or is it an issue ? Any advice will be much appreciated

**Comment by danking** [comment] 2023-03-10 02:11
Downgrading to 0.41.12 and pinning to that version for future proofing worked for us without any flags.

**Comment by WobblyRobbly** [comment] 2023-03-10 08:28
thanks @danking - I don't have access to the build repo for our image so have a dependency.... I might just have to add the permissions which is more in my control !!

**Comment by sethiay** [comment] 2023-03-20 05:41
The fix for this issue has been released in the latest GCSFuse release i.e. [v0.42.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.42.2). With GCSFuse v0.42.2, you can skip passing --enable-storage-client-library=false flag.
Marking this issue as closed. Please feel free to re-open in case you face the same issue again.

Thanks for your patience !

@WobblyRobbly , We have raised another [issue](https://github.com/GoogleCloudPlatform/gcsfuse/issues/1014) for the mount_gcsfuse not respecting bool values.

**Closed by sethiay** 2023-03-20 05:41 UTC
Labels: bug, next release

**Comment by danking** [comment] 2023-08-31 22:06
@sethiay can you clarify whether or not the underlying issue has been resolved?

The underlying issue is that 0.42.1 requires the requester to have `storage.buckets.get` permission on the bucket in question.

`storage.buckets.get` is not granted by roles like Storage Object Viewer, which is the standard role for read-only access to a bucket.

**Comment by sethiay** [comment] 2023-09-01 08:44
Hey @danking , from v0.42.2, GCSFuse doesn't require storage.buckets.get permission. Please check [this](https://cloud.google.com/storage/docs/gcsfuse-mount#authenticate_by_using_a_service_account) document for more information.

**Comment by ObliviousMonkey** [comment] 2023-09-26 14:11
I'm using `gcsfuse version 1.2.0 (Go version go1.21.0)` in Colab Enterprise with the following code:

```python
# Add the Cloud Storage FUSE distribution URL as a package source and import its public key
!export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s` && \
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list

!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
```

```python
# Update and install Cloud Storage FUSE and its dependency FUSE
!sudo -qq apt-get update
!sudo -qq apt-get install fuse gcsfuse
```

```python
# this creates the folder /content/gcs-bucket to be used as a mount point
!mkdir ./gcs-bucket
```

```python
!gcsfuse -o rw,allow_other -file-mode=777 -dir-mode=777 --foreground --debug_http --debug_gcs --debug_fuse --implicit-dirs <MY_BUCKET_NAME> ./gcs-bucket
```

Output:

```shell
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512880346167},"severity":"INFO","msg":"Start gcsfuse/1.2.0 (Go version go1.21.0) for app \"\" using mount point: /content/gcs-bucket\n"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512880398326},"severity":"INFO","msg":"Creating Storage handle..."}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512882185221},"severity":"INFO","msg":"Creating a mount at \"/content/gcs-bucket\"\n"}

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512882244418},"severity":"INFO","msg":"Creating a new server...\n"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512882255887},"severity":"INFO","msg":"Set up root directory for bucket MY_BUCKET_NAME"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512882285983},"severity":"TRACE","msg":"gcs: Req              0x0: <- ListObjects(\"\")"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960145390},"severity":"TRACE","msg":"gcs: Req              0x0: -> ListObjects(\"\") (77.846324ms): OK"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960245049},"severity":"INFO","msg":"Mounting file system \"MY_BUCKET_NAME\"..."}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960324910},"severity":"TRACE","msg":"fuse_debug: Beginning the mounting kickoff process"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960352388},"severity":"TRACE","msg":"fuse_debug: Parsing fuse file descriptor"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960374487},"severity":"TRACE","msg":"fuse_debug: Preparing for direct mounting"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960414844},"severity":"TRACE","msg":"fuse_debug: Successfully opened the /dev/fuse in blocking mode"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960449429},"severity":"TRACE","msg":"fuse_debug: Starting the unix mounting"}
{"time":{"timestampSeconds":1695736512,"timestampNanos":1695736512960496126},"severity":"ERROR","msg":"Error while mounting gcsfuse: mountWithStorageHandle: Mount: mount: permission denied\n"}
mountWithArgs: mountWithStorageHandle: Mount: mount: permission denied
```

From this issue it seems like it would not require permission to mount, so I cannot figure out what I am missing and how to work around this.

**Comment by vinisalazar** [comment] 2024-06-21 01:14
Any updates on this? I am experiencing the exact same problem.

`gcsfuse version 2.2.0 (Go version go1.22.3)`

**Comment by ankitaluthra1** [comment] 2024-06-24 13:42
@vinisalazar please open a new issue with steps to reproduce.
