### ISSUE TITLE
Mount Helper Behavior If CWD Contains Matching Directory

### ISSUE THREAD

**Issue by KermMartian** [GoogleCloudPlatform/gcsfuse#198] opened 2016-11-03 01:21 UTC
If you add an `/etc/fstab` entry resembling the following:
~~~~
bucket /mnt/bucket gcsfuse gcsfuse rw,noauto,user
~~~~
navigate to the /mnt folder (that already contains a `bucket` folder), and attempt to `mount bucket`, the following operation is attempted:
~~~~
Calling gcsfuse with arguments: -o noexec -o nosuid -o nodev -o rw /mnt/bucket /mnt/bucket
~~~~
Switching to another working directory that does not contain a `bucket` directory and trying again bypasses the issue. This appears to be a bug, since it seems to indeed be realizing that the requested /mnt/bucket refers to the fstab entry for the gcsfuse bucket `bucket`, but still uses /mnt/bucket as both the device and mountpoint arguments.

**Comment by jacobsa** [comment] 2016-11-03 01:48
(Probably a duplicate of #169.)

I think you have diagnosed this correctly, but as far as I can tell the bug lies in your system's `mount` command, which is unhelpfully turning `bucket` into an absolute path, not in gcsfuse. Please let me know if you can show otherwise, and also if you wind up filing a bug for `mount`.

**Closed by jacobsa** 2016-11-03 01:48 UTC
