### ISSUE TITLE
gcsfuse: Unable to mount the cloud storage in RHEL 8.7 - Just hangs

### ISSUE THREAD

**Issue by esidat** [GoogleCloudPlatform/gcsfuse#1142] opened 2023-05-24 17:30 UTC
```
[root@gcpo ~]# gcsfuse --implicit-dirs prj-netw-prod-wn-mf-01-bucket-01 /mnt
I0524 17:28:16.342215 2023/05/24 17:28:16.342173 Start gcsfuse/0.42.5 (Go version go1.20.3) for app "" using mount point: /mnt
```

**Comment by Tulsishah** [comment] 2023-05-25 03:39
Hi @esidat, Thanks for reaching out to us.

From The above log, it seems mounting is successful.
yet please share logs with --debug_gcs, debug_fuse and --log-format="text" flags enabled.

**Comment by Tulsishah** [comment] 2023-05-30 03:44
As I cannot reproduce the issue, for RCA, please share the output of the below commands.

1. gcsfuse --foreground --debug_gcs --debug_fuse <bucket-name> <mounted-dir>
2. gcsfuse --foreground --debug_gcs --debug_fuse --enable-storage-client-library=false <bucket-name> <mounted-dir>
3. gcsfuse --foreground --debug_gcs --debug_fuse --key-file=<key file path> <bucket-name> <mounted-dir>
4. gcsfuse --foreground --debug_gcs --debug_fuse --key-file=<key file path> --enable-storage-client-library=false <bucket-name> <mounted-dir>

Thanks,
Tulsi Shah

**Comment by raj-prince** [comment] 2023-06-24 12:46
@esidat Apology for the late response!

We got the same issue-ticket internally via customer-support team, but not sure that ticket was opened behalf of you or other customer. Till now, we are not able to finalise the solution. Currently we are depending upon more information from the customer. 

Below is the summary of discussion, we had on internal ticket:-

**Issue:** while mounting the bucket, internally GCSFuse calls ListObject api of GCS to check the connection and mounting setup is working fine or not. Mounting hangs in this call, with the below error.

**Error:** oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": dial tcp[ 199.36.153.10:443] http://199.36.153.10:443/: i/o timeout

We can clearly see, this is the issue while making connection with Oauth server.

Can you please also check - do you also get the same error? If not then please share the logs while mounting `gcsfuse` with the command mentioned by @Tulsishah.

Or you might try the below options:
1. Network is working fine on the system. 
2. Firewall rule for outgoing server is open.
3. Customer also mentioned that, setup is working with some proxy settings. But we haven't get any concrete information of proxy settings yet.

Thanks and Regards,
Prince Kumar.

**Comment by raj-prince** [comment] 2023-07-06 01:56
Closing this issue, as it is opened internally for the same customer.

I'll update the fix here also, if that would be useful for other customer.

**Closed as completed by raj-prince** 2023-07-06 01:56 UTC
Labels: bug, p1
