### ISSUE TITLE
Mount a single dir from bucket.

### ISSUE THREAD

**Issue by kernelt** [GoogleCloudPlatform/gcsfuse#124] opened 2015-09-04 20:27 UTC
Hi Aaron. Thank for you work. 
Gcsfuse can't mount a single dir from bucket, only whole bucket can be mounted. Can you add this feature, it would be useful in some situations.

**Comment by jacobsa** [comment] 2015-09-05 03:53
Could you explain why you need this, as opposed to simply setting your working directory (or using `chroot`) to the directory you're interested in?

**Comment by kernelt** [comment] 2015-09-06 14:28
Hi Aaron.
For an example. In our case, we have many users dir, that stored in one bucket. Some users need to use its dir through a ssh and for this goal the docker container is perfect - one container for one user (it's like a chroot). In a container, we want to add the user's dir from bucket via a gcsfuse, but the gcsfuse can't mount only one dir and we must mount a whole bucket in the container, but it is not acceptable for us, because in this way, a user can access to files of other users.

We don't use one bucket for each users, because it's too hard to maintain from servers and from programmer codes. Furthermore, we'll need to run as many gcsfuse proccess - one process for each users - it's too complex solution.

**Comment by jacobsa** [comment] 2015-09-06 21:13
Forgive me because I'm not very familiar with Docker at all, but looking at the documentation [here](https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume) it looks like you can provide a single directory from the host as a data volume for the container. So you would mount gcsfuse once on the host, then provide a sub-directory on each container.

Does that sound like it would work for you? I'm reluctant to add this feature because I've never heard of the corresponding feature in a traditional file system—I don't think I've heard of being able to mount only a sub-directory of an ext2 volume, for example.

**Comment by andrewgaul** [comment] 2015-09-06 21:26
@jacobsa s3fs allow mounting a subdirectory with the syntax `s3fs bucket:/remote/path /path/to/mountpoint`

**Comment by kernelt** [comment] 2015-09-06 21:42
@jacobsa 
Yes, you are totally right, docker has the option "-v". But it will be a big trouble when gcsfuse process crashed or exited (or other problem with it) on the host machine. If it happen, work all users in all containers will be stopped (stuck). We saw it when we were using the "-v" option to mount nfs dir from the host to container. After the nfs-server was rebooted/stoppped, all containers which used mounted nfs dir from the docker host, could not work properly.
I don't quite understand, what do you mean in your second paragraph?

**Comment by jacobsa** [comment] 2015-09-06 23:13
@kernelt: That's assuming that you run one gcsfuse process for the whole host, I think. You could still run one gcsfuse process per container, but use docker's `-v` feature to expose only a portion of the mounted directory to the corresponding container, right? Alternatively, it looks like Linux itself can do a similar thing with [bind mounts](http://unix.stackexchange.com/questions/198590/what-is-a-bind-mount).

What I meant by the second paragraph above: there is a cost to each feature I add, so I have to choose wisely what is worth adding. I look to "real" file systems (ext2/3/4, HFS+, etc) for guidance on what makes sense to add, because if those file systems are lacking a feature it's likely that there is some other way for users to accomplish what they need. In this case it looks like the answer is `mount --bind`.

@andrewgaul: That's interesting to know, thanks for the data point.

**Comment by kernelt** [comment] 2015-09-07 19:26
@jacobsa 
If I understood properly, your advice is: run as many gcsfuse process as we have users (containers) on the docker host machine, and then, use a "-v" option of  the docker to mount only one dir to a container. Correct? If so, in this case, you are right, we don't have the problem I described above concerning hanging of containers if suddenly we have a gcsfuse issue. However, I think it will be unnecessary (superfluous) to keep in each folder on the docker host machine all users folders (because we have only a one bucket), isn't it?

**Comment by jacobsa** [comment] 2015-09-07 22:51
That's what I'm recommending (or using `mount --bind`), yes. I don't see what the downside of doing this is—is there some actual cost you are concerned about when you say it's superfluous to do this? By far the most important cost here is running one gcsfuse process per user, but you'd need to do that either way. If you don't interact with other directories in each mount, then it's as if they didn't even exist, since gcsfuse never looks them up, never assigns an inode number, etc.

(This is all theorizing on my part; let me know if you find I'm wrong and run into an actual measurable problem.)

**Comment by jacobsa** [comment] 2015-09-08 05:35
Closing this because I think docker's `-v` option or `mount --bind` are the way to deal with this, as you would with any other sort of directory. But if you measure a problem with this, let me know.

**Closed by jacobsa** 2015-09-08 05:35 UTC

**Comment by kernelt** [comment] 2015-11-04 21:49
Hi Aaron. Long time no see you :-)
Because with such usage, all containers will use single gcsfuse process and if we launch "cat file" for each conteiners, it will work slower than if each container would have used its own gcsfuse. Is it correct?
We can of course mount same bucket via 100 of different gcsfuse processes and then connect one folder from each process into container. But then our host machine on which docker works will get slow, because each time gcsfuse will have to read data from an entire bucket , not from a single folder.
So, would if be possible to mount a specific folder instead of full bucket?

**Comment by jacobsa** [comment] 2015-11-04 23:52
I'm sorry, I don't understand your question. Could you please precisely and separately describe the two setups you are envisioning, and then tell me in what way you expect them to perform differently?

**Comment by kmelevskiy** [comment] 2015-11-24 18:58
Hi Aaron. 
For several reasons it would be very nice to mount not just full bucket, but also one or multiple folders of the bucket. It will give us much more flexibility to deal with mounting user data to container. Would it be possible for you to extend   gcsfuse functionality by adding the option of mounting one or list of folders in bucket?
 This option will make it easy to manage of data  maintenance in bucket, as only needed folder will be mounted to the container.  It will enhances security of using gcsfuse in this case by restricting access to only needed folder. It also make gcsfuse work faster as only necessary data will be read.
 I am pretty sure that many users will benefit from it.

**Comment by jacobsa** [comment] 2015-12-10 02:02
@kmelevskiy: Sorry for the slow response; I've been on vacation. What are the "several reasons" you refer to? Why can you not simply run gcsfuse multiple times?

**Comment by kmelevskiy** [comment] 2015-12-11 16:29
Hi Aaron,
Several reasons include:
-our requirement to dynamically change data access of each Docker container (without shutting it  down) to many folders coming from many buckets. We don't know how to connect dynamically from inside docker container to requested bucket "folder" without showing other unnecessary folders.
-desire to reduce number of links from Docket container to single gcsfuse process connecting to bucket with shareable folder that can potentially can be accessible to all users. 
-necessity to  reduce dependency of all containers on single access point to one bucket and increase stability of data access if gsfuse of shared data get down. 
Looking forward to hear your thoughts.

**Comment by jacobsa** [comment] 2015-12-14 08:32
Thanks. Taking this point by point:

> our requirement to dynamically change data access of each Docker container (without shutting it down) to many folders coming from many buckets. We don't know how to connect dynamically from inside docker container to requested bucket "folder" without showing other unnecessary folders.

Why would this be doable with a `gcsfuse --only-dir subdir/` option and not with docker's `-v` option or `mount --bind`?

> desire to reduce number of links from Docket container to single gcsfuse process connecting to bucket with shareable folder that can potentially can be accessible to all users. 

It's been implied several times in this thread that it's desirable to have fewer gcsfuse processes, but I haven't seen a reason why. Why is it problematic to have multiple gcsfuse processes? I see only benefits of doing so. Unless you're experiencing high RAM usage?

> necessity to reduce dependency of all containers on single access point to one bucket and increase stability of data access if gcsfuse of shared data get down. 

I think you're saying that you want multiple gcsfuse processes so that users don't have gcsfuse as a single point of failure. Using docker's `-v` or `mount --bind` doesn't preclude doing this...

**Comment by jacobsa** [comment] 2015-12-22 00:50
@kernelt, @andrewgaul, @kmelevskiy: in #143 @suhas22 asked me for this feature again. They gave me a good description of what they were trying to do, to the point where I was able to reproduce the issue and see that gcsfuse appears to be incompatible with an sftp chroot.

So I will probably wind up implementing this feature. Please follow along in #143. Thanks for your patience.

**Comment by jacobsa** [comment] 2015-12-22 05:23
Update: the `--only-dir` flag exists since 62dd0425f4618bb5fc8e1797ea02a1a93852b1ce. Please try it and let me know how it works for you.

**Comment by kernelt** [comment] 2016-01-09 15:47
We tested this option (--only-dir) and it seems it works as we expected, thanks!

**Comment by kmelevskiy** [comment] 2016-01-09 23:51
Hi Asron,
Sorry for delay with my response- I was on hollidays.
Collegue of mine @kernelt have tested new option (--only-dir) which works
as we needed.
Thanks a lot for your kind support.

Regards,
Andrey

On Thursday, 10 December 2015, Aaron Jacobs <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @kmelevskiy <https://github.com/kmelevskiy>: Sorry for the slow response;
> I've been on vacation. What are the "several reasons" you refer to? Why can
> you not simply run gcsfuse multiple times?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcsfuse/issues/124#issuecomment-163462974>
> .
>


-- 
Kind regards,
Andrey Khmelevskiy

С уважением,
Андрей Хмелевский

**Comment by len5** [comment] 2018-07-20 09:17
Hey!
very very late but...
so,
to mount specific subdirectory of a bucket in a mount point:

--> command
gcsfuse -o option1,option2 --only-dir sub_dirirectory/ -key-file=/path/to/key.json bucket_name /path/to/mount/point
--> fstab
bucket_name /path/to/mount/point gcsfuse rw,user,key_file=/path/to/key.json,only_dir=sub_directory
